workflows:
    b2b_flow_checkout:
        transitions:
            __start__:
                step_to: enter_billing_address

            start_from_shoppinglist:
                step_to: enter_billing_address

            #Starts checkout as guest
            start_from_shoppinglist_as_guest:
                step_to: enter_credentials_step
                is_start: true
                is_unavailable_hidden: true #
                transition_definition: start_from_shoppinglist_as_guest_definition
                frontend_options:
                    icon: fa-briefcase
                init_routes:
                    - oro_shopping_list_frontend_view
                acl_resource: [CHECKOUT_CREATE, $.result.shoppingList]

            # Continue checkout as guest from credentias step
            continue_checkout_as_guest:
                step_to: enter_billing_address
                transition_definition: back_to_billing_address_definition
                frontend_options:
                    icon: fa-briefcase
                    is_checkout_continue: true

            start_checkout_as_guest_system:
                step_to: enter_credentials_step
                is_hidden: true
                transition_definition: start_checkout_as_guest_system_definition

            start_from_quickorderform:
                step_to: enter_billing_address

            finish_checkout:
                step_to: order_created

            payment_error:
                step_to: enter_payment

            continue_to_shipping_address:
                step_to: enter_shipping_address
                transition_definition: continue_to_shipping_address_definition
                display_type: page
                frontend_options:
                    is_checkout_continue: true
                    is_checkout_show_errors: true
                form_options:
                    form_init:
                        - '@generate_checkout_state_snapshot':
                            entity: $checkout
                            attribute: $.result.initCheckoutState
                    attribute_fields:
                        billing_address:
                            form_type: Oro\Bundle\CheckoutBundle\Form\Type\CheckoutAddressType
                            options:
                                object: $checkout
                                isEditEnabled: true
                                addressType: 'billing'
                                required: true
                                translation_domain: messages
                                constraints:
                                    - Valid: ~
                                    - NotBlank: ~
                                    - Oro\Bundle\AddressBundle\Validator\Constraints\NameOrOrganization: ~
                                disabled: $disallow_billing_address_edit
                        save_billing_address:
                            form_type: Oro\Bundle\CheckoutBundle\Form\Type\SaveAddressType
                            options:
                        ship_to_billing_address:
                            form_type: Oro\Bundle\CheckoutBundle\Form\Type\ShipToBillingAddressType
                            options:
                        state_token:
                            form_type: Symfony\Component\Form\Extension\Core\Type\HiddenType
                            options:
                                data: $internal_state_token
                        email:
                            form_type: Oro\Bundle\CustomerBundle\Form\Type\CustomerVisitorEmailAddressType
            continue_to_shipping_method:
                step_to: enter_shipping_method
                transition_definition: continue_to_shipping_method_definition
                display_type: page
                frontend_options:
                    is_checkout_continue: true
                    is_checkout_show_errors: true
                form_options:
                    form_init:
                        - '@generate_checkout_state_snapshot':
                            entity: $checkout
                            attribute: $.result.initCheckoutState
                    attribute_fields:
                        shipping_address:
                            form_type: Oro\Bundle\CheckoutBundle\Form\Type\CheckoutAddressType
                            options:
                                object: $checkout
                                isEditEnabled: true
                                addressType: 'shipping'
                                required: true
                                disabled: $disallow_shipping_address_edit
                                translation_domain: messages
                                constraints:
                                    - Valid: ~
                                    - NotBlank: ~
                                    - Oro\Bundle\AddressBundle\Validator\Constraints\NameOrOrganization: ~
                        save_shipping_address:
                            form_type: Oro\Bundle\CheckoutBundle\Form\Type\SaveAddressType
                            options:
                        ship_to_billing_address:
                            form_type: Oro\Bundle\CheckoutBundle\Form\Type\ShipToBillingAddressType
                            options:
                        state_token:
                            form_type: Symfony\Component\Form\Extension\Core\Type\HiddenType
                            options:
                                data: $internal_state_token

            continue_to_payment:
                step_to: enter_payment
                transition_definition: continue_to_payment_definition
                frontend_options:
                    is_checkout_continue: true
                    is_checkout_show_errors: true
                    page_component_module: 'orocheckout/js/app/components/shipping-transition-button-component'
                form_options:
                    form_init:
                        - '@generate_checkout_state_snapshot':
                            entity: $checkout
                            attribute: $.result.initCheckoutState
                        - '@call_service_method':
                            service: oro_checkout.action.default_shipping_method_setter
                            method: setDefaultShippingMethod
                            method_parameters: [$checkout]
                    attribute_fields:
                        shipping_method:
                            options:
                                constraints:
                                    - NotBlank: ~
                        shipping_method_type:
                            options:
                                constraints:
                                    - NotBlank: ~
                        state_token:
                            form_type: Symfony\Component\Form\Extension\Core\Type\HiddenType
                            options:
                                data: $internal_state_token

            continue_to_order_review:
                step_to: order_review
                transition_definition: continue_to_order_review_definition
                frontend_options:
                    is_checkout_continue: true
                    is_checkout_show_errors: true
                    page_component_module: 'orocheckout/js/app/components/payment-transition-button-component'
                form_options:
                    form_init:
                        - '@assign_value': [$payment_validate, true]
                        - '@call_service_method':
                            service: oro_payment.provider.payment_transaction
                            method: getActiveValidatePaymentTransaction
                            method_parameters: [$payment_method]
                            attribute: $.result.validatePaymentTransaction
                        - '@assign_value':
                            conditions:
                                '@not_empty': [$.result.validatePaymentTransaction]
                            parameters: [$payment_validate, false]
                        - '@generate_checkout_state_snapshot':
                            entity: $checkout
                            attribute: $.result.initCheckoutState
                    attribute_fields:
                        payment_method: ~
                        payment_validate:
                            form_type: Symfony\Component\Form\Extension\Core\Type\CheckboxType
                        payment_save_for_later:
                            form_type: Symfony\Component\Form\Extension\Core\Type\CheckboxType
                        state_token:
                            form_type: Symfony\Component\Form\Extension\Core\Type\HiddenType
                            options:
                                data: $internal_state_token
                        additional_data:
                            form_type: Symfony\Component\Form\Extension\Core\Type\HiddenType

            back_to_billing_address:
                step_to: enter_billing_address
                transition_definition: clear_payment_method_and_recalculate_state_definition
                is_unavailable_hidden: true
                frontend_options:
                    is_checkout_back: true

            back_to_shipping_address:
                step_to: enter_shipping_address
                transition_definition: clear_payment_method_and_recalculate_state_definition
                is_unavailable_hidden: true
                frontend_options:
                    is_checkout_back: true

            back_to_shipping_address_on_fail_address:
                step_to: enter_shipping_address
                transition_definition: unblock_and_recalculate_definition
                is_hidden: true

            back_to_shipping_method:
                step_to: enter_shipping_method
                transition_definition: clear_payment_method_and_recalculate_state_definition
                is_unavailable_hidden: true
                frontend_options:
                    is_checkout_back: true

            back_to_payment:
                step_to: enter_payment
                transition_definition: recalculate_state_definition
                is_unavailable_hidden: true
                frontend_options:
                    is_checkout_back: true

            verify_payment:
                step_to: enter_payment
                transition_definition: verify_payment_definition
                is_hidden: true
                frontend_options:
                    is_checkout_verify: true

            place_order:
                step_to: order_review
                transition_definition: place_order_definition
                display_type: page
                frontend_options:
                    is_checkout_continue: true
                    is_checkout_show_errors: true
                form_options:
                    form_init:
                        - '@generate_checkout_state_snapshot':
                            entity: $checkout
                            attribute: $.result.initCheckoutState
                        - '@assign_value': [$late_registration.email, $visitor_email]

                    attribute_fields:
                        remove_source: ~
                        po_number: ~
                        ship_until:
                            form_type: Oro\Bundle\CheckoutBundle\Form\Type\CheckoutShipUntilType
                            options:
                                checkout: $checkout
                        late_registration:
                          form_type: Oro\Bundle\CheckoutBundle\Form\Type\LateRegistrationType
                          options:
                              required: true
                        customer_notes:
                            form_type: Symfony\Component\Form\Extension\Core\Type\TextareaType
                        state_token:
                            form_type: Symfony\Component\Form\Extension\Core\Type\HiddenType
                            options:
                                data: $internal_state_token
