services:
    oro_seo.tests.skipped_file_systems:
        class: Oro\Bundle\GaufretteBundle\Tests\Functional\Environment\SkippedGaufretteFileSystemProvider
        decorates: oro_gaufrette.tests.skipped_file_systems
        arguments:
            - '@.inner'
            - [ 'sitemaps_tmp_data' ]
