api:
    entities:
        Oro\Bundle\ProductBundle\Entity\Product:
            documentation_resource: '@OroPricingBundle/Resources/doc/api_frontend/product.md'
            fields:
                prices:
                    data_type: objects
                    property_path: _

        Oro\Bundle\ProductBundle\Api\Model\ProductSearch:
            documentation_resource: '@OroPricingBundle/Resources/doc/api_frontend/product_search.md'
            fields:
                minimalPrices:
                    data_type: objects
                    property_path: _
                    depends_on:
                        # see Oro\Bundle\PricingBundle\Api\Processor\UpdateDependsOnConfigForMinimalPriceField
                        - text.product_units
