entity_config:
    sharding:
        # You can find out more about attributes in the documentation: https://doc.oroinc.com/backend/configuration/annotation/config/#sharding
        entity:
            items:
                discrimination_field: ~
