oro_permissions:
    RECALCULATE:
        label: oro.pricing.permission.recalculate.label
        group_names: ""
        apply_to_all: false
        apply_to_entities:
            - 'Oro\Bundle\PricingBundle\Entity\PriceList'
