placeholders:
    placeholders:
        product_index_sidebar:
            items:
                product_sidebar_prices_config_selector: ~
        oro_product_quick_add_additional_fields:
            items:
                quick_add_subtotal: ~
        oro_product_quick_add_collection_after:
            items:
                price_templates: ~

    items:
        product_sidebar_prices_config_selector:
            action: Oro\Bundle\PricingBundle\Controller\ProductController::sidebarAction
        quick_add_subtotal:
            template: '@@OroPricing/Product/subtotal.html.twig'
        price_templates:
            template: '@@OroPricing/Product/price_templates.html.twig'
