search:
    Oro\Bundle\PricingBundle\Entity\PriceList:
        alias:                          oro_pricing_price_list
        route:
            name:                       oro_pricing_price_list_view
            parameters:
                id:                     id
        search_template:                '@OroPricing/PriceList/searchResult.html.twig'
        fields:
            -
                name:                   name
                target_type:            text
                target_fields:          [name]
