services:
    _defaults:
        public: true

    Oro\Bundle\OrderBundle\Controller\OrderController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }

    Oro\Bundle\OrderBundle\Controller\AjaxOrderController:
        calls:
            - [ 'setContainer', [ '@Psr\Container\ContainerInterface' ] ]
        tags:
            - { name: container.service_subscriber }

    Oro\Bundle\OrderBundle\Controller\Frontend\OrderController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
            - { name: container.service_subscriber, id: oro_checkout.helper.check_compare }

    Oro\Bundle\OrderBundle\Controller\Frontend\ProductsController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
