services:
    oro_order.tests.provider.configuration.stub:
        class: Oro\Bundle\OrderBundle\Tests\Functional\Stub\OrderConfigurationProviderStub
        decorates: oro_order.provider.configuration
        decoration_priority: -1000
        parent: oro_order.provider.configuration

    oro_order.tests.entity_name_resolver.data_loader:
        class: Oro\Bundle\OrderBundle\Tests\Functional\Environment\TestEntityNameResolverDataLoader
        decorates: oro_entity.tests.entity_name_resolver.data_loader
        arguments:
            - '@.inner'
