datagrids:
    frontend-quotes-grid:
        acl_resource: oro_sale_quote_frontend_view
        extended_entity_name: 'Oro\Bundle\SaleBundle\Entity\Quote'
        options:
            frontend: true
            entityHint: oro.sale.quote.entity_plural_label
            entity_pagination: true
        source:
            type:         orm
            query:
                select:
                    - quote.id
                    - quote.qid
                    - CONCAT(quoteCustomerUser.firstName, ' ', quoteCustomerUser.lastName) as customerUserName
                    - customerStatus.name as customerStatusName
                    - customerStatus.id as customerStatusId
                    - quote.createdAt
                    - quote.validUntil
                    - quote.poNumber
                    - quote.shipUntil
                from:
                    - { table: 'Oro\Bundle\SaleBundle\Entity\Quote', alias: quote }
                join:
                    left:
                        - { join: quote.customerUser, alias: quoteCustomerUser }
                        - { join: quote.customer_status, alias: customerStatus }
            hints:
                - HINT_TRANSLATABLE
        columns:
            qid:
                label:         oro.frontend.sale.quote.qid.label
            customerStatusName:
                label:         oro.frontend.sale.quote.customer_status.label
                renderable:    false
            poNumber:
                label:         oro.frontend.sale.quote.po_number.label
            shipUntil:
                label:         oro.frontend.sale.quote.ship_until.label
                frontend_type: date
            createdAt:
                label:         oro.ui.created_at
                frontend_type: datetime
            validUntil:
                label:         oro.frontend.sale.quote.valid_until.label
                frontend_type: datetime
            customerUserName:
                label:         oro.frontend.sale.quote.customer_user.label
        properties:
            id: ~
            view_link:
                type:  url
                route: oro_sale_quote_frontend_view
                params: [ id ]
            view_aria_label:
                type:   translatable
                key:    oro.frontend.sale.quote.action.view.aria_label
                params: [qid]
        sorters:
            columns:
                qid:
                    data_name: quote.qid
                customerUserName:
                    data_name: customerUserName
                customerStatusName:
                    data_name: customerStatusName
                poNumber:
                    data_name: quote.poNumber
                shipUntil:
                    data_name: quote.shipUntil
                createdAt:
                    data_name: quote.createdAt
                validUntil:
                    data_name: quote.validUntil
            disable_default_sorting: true
        filters:
            columns:
                qid:
                    type:      string
                    data_name: quote.qid
                customerUserName:
                    type:      string
                    data_name: customerUserName
                customerStatusName:
                    type:       enum
                    data_name:  customerStatusId
                    enum_code:  quote_customer_status
                    renderable: false
                poNumber:
                    type:      string
                    data_name: quote.poNumber
                shipUntil:
                    type:      date
                    data_name: quote.shipUntil
                validUntil:
                    type:      datetime
                    data_name: quote.validUntil
                createdAt:
                    type:      datetime
                    data_name: quote.createdAt
        actions:
            view:
                type:          navigate
                label:         oro.grid.action.view
                ariaLabel:     view_aria_label
                link:          view_link
                icon:          eye
                rowAction:     true
