api:
    entities:
        Oro\Bundle\WebsiteSearchBundle\SearchResult\Entity\SearchResultHistory:
            documentation_resource: '@OroWebsiteSearchBundle/Resources/doc/api/search_results_history.md'
            disable_meta_properties: [ title ]
            fields:
                normalizedSearchTermHash:
                    exclude: true
                searchSession:
                    exclude: true
            actions:
                create: false
                update: false
                delete: false
                delete_list: false

        Oro\Bundle\WebsiteSearchBundle\SearchResult\Entity\SearchTermReport:
            documentation_resource: '@OroWebsiteSearchBundle/Resources/doc/api/search_term_report.md'
            disable_meta_properties: [ title ]
            fields:
                normalizedSearchTermHash:
                    exclude: true
            actions:
                create: false
                update: false
                delete: false
                delete_list: false
