app-modules:
    - oroinventory/js/app/modules/validator-constraints-module
dynamic-imports:
    commons:
        - oroinventory/js/validator/decimals-number
    orodatagrid:
        - oroinventory/js/datagrid/builder/inventory-status-builder
        - oroinventory/js/datagrid/builder/level-quantity-builder
    orosale:
        - oroinventory/js/app/views/quantity-editor-view
