placeholders:
    items:
        oro_product_manage_inventory_button:
            template: '@@OroInventory/Product/inventoryButton.html.twig'
            applicable:
                - '@oro_ui.placeholder.filter->isInstanceOf($entity$, Oro\Bundle\ProductBundle\Entity\Product)'
                - '@oro_frontend.placeholder.filter->isBackendRoute()'

        oro_product_manage_inventory_link:
            template: '@@OroInventory/Product/inventoryLink.html.twig'
            applicable:
                - '@oro_ui.placeholder.filter->isInstanceOf($entity$, Oro\Bundle\ProductBundle\Entity\Product)'
                - '@oro_frontend.placeholder.filter->isBackendRoute()'
