system_configuration:
    groups:
        product_options:
            title: oro.inventory.system_configuration.groups.product_options.title
            icon: 'fa-cogs'
        product_inventory_options:
            title: oro.inventory.system_configuration.groups.product_inventory_options.title
        upcoming_products:
            title: oro.inventory.system_configuration.groups.upcoming_products.title
        limitations:
            title: oro.inventory.system_configuration.groups.limitations.title
            icon: 'fa-minus'
        product_quantity_limitations:
            title: oro.inventory.system_configuration.groups.product_quantity_limitations.title

    fields:
        oro_inventory.manage_inventory:
            data_type: boolean
            type: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            search_type: choice
            options:
                label: oro.inventory.system_configuration.fields.manage_inventory.label
                choice_translation_domain: messages
                choices:
                    oro.inventory.manage_inventory.choice.false: 0
                    oro.inventory.manage_inventory.choice.true: 1
        oro_inventory.highlight_low_inventory:
            data_type: boolean
            type: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            search_type: choice
            options:
                tooltip: oro.inventory.system_configuration.fields.highlight_low_inventory.tooltip
                label: oro.inventory.system_configuration.fields.highlight_low_inventory.label
                choice_translation_domain: messages
                choices:
                    oro.inventory.highlight_low_inventory.choice.false: 0
                    oro.inventory.highlight_low_inventory.choice.true: 1
        oro_inventory.backorders:
            data_type: boolean
            type: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            search_type: choice
            options:
                label: oro.inventory.system_configuration.fields.backorders.label
                choice_translation_domain: messages
                choices:
                    oro.inventory.backorders.choice.false: 0
                    oro.inventory.backorders.choice.true: 1
        oro_inventory.decrement_inventory:
            data_type: boolean
            type: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            search_type: choice
            options:
                tooltip: oro.inventory.system_configuration.fields.decrement_inventory.tooltip
                label: oro.inventory.system_configuration.fields.decrement_inventory.label
                choice_translation_domain: messages
                choices:
                    oro.inventory.decrement_inventory.choice.false: 0
                    oro.inventory.decrement_inventory.choice.true: 1
        oro_inventory.inventory_threshold:
            data_type: decimal
            type: Symfony\Component\Form\Extension\Core\Type\NumberType
            search_type: text
            options:
                label: oro.inventory.system_configuration.fields.inventory_threshold.label
                required: true
                scale: 1
                constraints:
                    - NotBlank: ~
                    - Oro\Bundle\ValidationBundle\Validator\Constraints\NumericRange:
                        min: -100000000
                        max: 100000000
        oro_inventory.low_inventory_threshold:
            data_type: decimal
            type: Symfony\Component\Form\Extension\Core\Type\NumberType
            search_type: text
            options:
                tooltip: oro.inventory.system_configuration.fields.low_inventory_threshold.tooltip
                label: oro.inventory.system_configuration.fields.low_inventory_threshold.label
                required: true
                scale: 1
                constraints:
                    - NotBlank: ~
                    - Oro\Bundle\ValidationBundle\Validator\Constraints\NumericRange:
                        min: -100000000
                        max: 100000000
        oro_inventory.minimum_quantity_to_order:
            data_type: decimal
            type: Symfony\Component\Form\Extension\Core\Type\NumberType
            search_type: text
            priority: 10
            options:
                label: oro.inventory.system_configuration.fields.minimum_quantity_to_order.label
                required: false
                scale: 2
                constraints:
                    - Oro\Bundle\ValidationBundle\Validator\Constraints\NumericRange:
                        min: -100000000
                        max: 100000000
        oro_inventory.maximum_quantity_to_order:
            data_type: decimal
            type: Symfony\Component\Form\Extension\Core\Type\NumberType
            search_type: text
            priority: 5
            options:
                label: oro.inventory.system_configuration.fields.maximum_quantity_to_order.label
                required: false
                scale: 2
                constraints:
                    - Oro\Bundle\ValidationBundle\Validator\Constraints\NumericRange:
                        min: -100000000
                        max: 100000000
        oro_inventory.hide_labels_past_availability_date:
            data_type: boolean
            type: Oro\Bundle\ConfigBundle\Form\Type\ConfigCheckbox
            options:
                required: false
                tooltip: oro.inventory.system_configuration.fields.hide_labels_past_availability_date.tooltip
                label: oro.inventory.system_configuration.fields.hide_labels_past_availability_date.label
    tree:
        system_configuration:
            commerce:
                children:
                    product_inventory:
                        children:
                            product_options:
                                priority: 90
                                children:
                                    product_inventory_options:
                                        children:
                                            - oro_inventory.manage_inventory
                                            - oro_inventory.inventory_threshold
                                            - oro_inventory.backorders
                                            - oro_inventory.decrement_inventory
                                            - oro_inventory.highlight_low_inventory
                                            - oro_inventory.low_inventory_threshold
                                    upcoming_products:
                                        children:
                                            - oro_inventory.hide_labels_past_availability_date
                            limitations:
                                priority: 80
                                children:
                                    product_quantity_limitations:
                                        children:
                                            - oro_inventory.minimum_quantity_to_order
                                            - oro_inventory.maximum_quantity_to_order
