styles:
    inputs:
        - 'bundles/oroshoppinglist/default/scss/settings/global-settings.scss'

        - 'bundles/oroshoppinglist/default/scss/variables/matrix-order-widget-config.scss'
        - 'bundles/oroshoppinglist/default/scss/variables/shopping-lists-config.scss'
        - 'bundles/oroshoppinglist/default/scss/variables/shopping-lists-popup-config.scss'
        - 'bundles/oroshoppinglist/default/scss/variables/shopping-list-dropdown-config.scss'
        - 'bundles/oroshoppinglist/default/scss/variables/shoppinglist-popover-config.scss'
        - 'bundles/oroshoppinglist/default/scss/variables/shopping-list-widget-config.scss'
        - 'bundles/oroshoppinglist/default/scss/variables/shopping-lists-units-config.scss'
        - 'bundles/oroshoppinglist/default/scss/variables/shopping-lists-outer-config.scss'

        - 'bundles/oroshoppinglist/default/scss/variables/responsive-shopping-list-grid/grid-line-items-config.scss'
        - 'bundles/oroshoppinglist/default/scss/variables/responsive-shopping-list-grid/grid-side-effects-config.scss'
        - 'bundles/oroshoppinglist/default/scss/variables/responsive-shopping-list-grid/responsive-shopping-list-grid-config.scss'
        - 'bundles/oroshoppinglist/default/scss/variables/responsive-shopping-list-grid/responsive-shopping-list-grid-view.scss'
        - 'bundles/oroshoppinglist/default/scss/variables/responsive-shopping-list-grid/responsive-shopping-list-grid-edit-config.scss'
        - 'bundles/oroshoppinglist/default/scss/variables/inline-editing/line-item-editing-config.scss'
        - 'bundles/oroshoppinglist/default/scss/variables/cart-list-empty-config.scss'
        - 'bundles/oroshoppinglist/default/scss/variables/my-shopping-list-owner-wrapper-config.scss'

        - 'bundles/oroshoppinglist/default/scss/components/cart-list-empty.scss'
        - 'bundles/oroshoppinglist/default/scss/components/products-widget.scss'
        - 'bundles/oroshoppinglist/default/scss/components/shopping-list-dropdown.scss'
        - 'bundles/oroshoppinglist/default/scss/components/shopping-lists-modify.scss'
        - 'bundles/oroshoppinglist/default/scss/components/shopping-lists-notes-modal.scss'
        - 'bundles/oroshoppinglist/default/scss/components/shopping-lists-outer.scss'
        - 'bundles/oroshoppinglist/default/scss/components/shopping-lists-units.scss'
        - 'bundles/oroshoppinglist/default/scss/components/shoppinglist-popover.scss'

        - 'bundles/oroshoppinglist/default/scss/components/shopping-list-widget.scss'
        - 'bundles/oroshoppinglist/default/scss/components/responsive-shopping-list-grid/responsive-shopping-list-layout.scss'
        - 'bundles/oroshoppinglist/default/scss/components/responsive-shopping-list-grid/grid-line-items.scss'
        - 'bundles/oroshoppinglist/default/scss/components/responsive-shopping-list-grid/responsive-shopping-list-grid.scss'
        - 'bundles/oroshoppinglist/default/scss/components/responsive-shopping-list-grid/responsive-shopping-list-grid-view.scss'
        - 'bundles/oroshoppinglist/default/scss/components/responsive-shopping-list-grid/responsive-shopping-list-grid-edit.scss'
        - 'bundles/oroshoppinglist/default/scss/components/responsive-shopping-list-grid/grid-side-effects.scss'
        - 'bundles/oroshoppinglist/default/scss/components/shopping-list-notes.scss'
        - 'bundles/oroshoppinglist/default/scss/components/inline-editing/line-item-editing.scss'
        - 'bundles/oroshoppinglist/default/scss/components/shopping-list-move-action.scss'
        - 'bundles/oroshoppinglist/default/scss/components/matrix-order-widget.scss'
        - 'bundles/oroshoppinglist/default/scss/components/shopping-lists.scss'
        - 'bundles/oroshoppinglist/default/scss/components/shopping-lists-popup.scss'
        - 'bundles/oroshoppinglist/default/scss/components/my-shopping-list-owner-wrapper.scss'

print_styles:
    inputs:
        - 'bundles/oroshoppinglist/default/scss/components/shopping-list-widget-print.scss'
