services:
    _defaults:
        public: true

    Oro\Bundle\UPSBundle\Controller\AjaxUPSController:
        calls:
            - [setContainer, ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
