services:
    oro_ups.form.type.transport_settings:
        class: Oro\Bundle\UPSBundle\Form\Type\UPSTransportSettingsType
        arguments:
            - "@oro_ups.provider.transport"
            - '@oro_shipping.system_shipping_origin_provider'
        tags:
            - { name: form.type }

    oro_ups.form.type.shipping_method_config_options:
        class: Oro\Bundle\UPSBundle\Form\Type\UPSShippingMethodOptionsType
        arguments:
            - '@oro_currency.rounding.price_rounding_service'
        tags:
            - { name: form.type }
