services:
    Oro\Bundle\VisibilityBundle\Command\VisibilityCacheBuildCommand:
        public: false
        class: Oro\Bundle\VisibilityBundle\Command\VisibilityCacheBuildCommand
        tags:
            - { name: console.command }
