services:
    _defaults:
        public: true

    Oro\Bundle\VisibilityBundle\Controller\ProductVisibilityController:
        calls:
            - [setContainer, ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
