services:
    oro_product.layout.type.quick_add_validation_container:
        parent: oro_layout.block_type.abstract_configurable
        calls:
            - [setOptionsConfig, [{collection: {required: true}}]]
            - [setName, ['quick_add_validation_container']]
            - [setParent, ['container']]
        tags:
             - { name: layout.block_type, alias: quick_add_validation_container }

    oro_product.layout.type.import_invalid_items_warning:
        parent: oro_layout.block_type.abstract_configurable
        calls:
            - [setOptionsConfig, [{collection: {required: true}}]]
            - [setName, ['invalid_items_warning']]
        tags:
             - { name: layout.block_type, alias: invalid_items_warning }

    # Component added back for theme layout BC from version 5.0
    oro_ui.layout.block_type.vertical_container:
        parent: oro_layout.block_type.abstract_configurable_container
        calls:
            - [setName, ['vertical_container']]
        tags:
            - { name: layout.block_type, alias: vertical_container }

    oro_product.layout.type.import_validation_items:
        parent: oro_layout.block_type.abstract_configurable
        calls:
            - [setOptionsConfig, [{collection: {required: true}}]]
            - [setName, ['import_validation_items']]
        tags:
             - { name: layout.block_type, alias: import_validation_items }

    oro_product.layout.type.product_view_container:
        parent: oro_layout.block_type.abstract_configurable_container
        calls:
            -
                - setOptionsConfig
                -
                    -
                        parentProduct: ~
                        product: {required: true}
                        productTheme: {default: null}
            - [setName, ['product_view_container']]
        tags:
             - { name: layout.block_type, alias: product_view_container }

    oro_product.layout.type.product_view_microdata_container:
        parent: oro_layout.block_type.abstract_configurable_container
        calls:
            -
                - setOptionsConfig
                -
                    -
                        microdataWithoutPricesDisabled: {required: true}
                        schemaOrgDescriptionEnabled: {default: false} # Component added back for theme layout BC from version 5.0
                        schemaOrgDescription: {required: true}
                        productPrices: {required: true}
                        product: {required: false} # Made false for theme layout BC compatibility, better solutions might exist
            - [setName, ['product_view_microdata_container']]
        tags:
            - { name: layout.block_type, alias: product_view_microdata_container }

    oro_product.layout.type.product_datagrid:
        parent: oro_layout.block_type.abstract_configurable_container
        calls:
            - [setOptionsConfig, [{current_row_view: {required: true}}]]
            - [setName, ['product_datagrid']]
            - [setParent, ['datagrid']]
        tags:
             - { name: layout.block_type, alias: product_datagrid }

    oro_product.layout.type.product_datagrid_options:
        parent: oro_layout.block_type.abstract_configurable_container
        calls:
            - [setOptionsConfig, [{current_row_view: {required: true}}]]
            - [setName, ['product_datagrid_options']]
        tags:
             - { name: layout.block_type, alias: product_datagrid_options }

    oro_product.block_type.attribute_product_images:
        parent: oro_layout.block_type.abstract_configurable
        calls:
            -
                - setOptionsConfig
                -
                    -
                        popup_gallery: {default: true}
            - [setName, ['attribute_product_images']]
            - [setParent, ['attribute_text']]
        tags:
             - { name: layout.block_type, alias: attribute_product_images }

    oro_product.block_type.attribute_product_brand:
        parent: oro_layout.block_type.abstract_configurable
        calls:
            - [setOptionsConfig, [{translated_value: {default: '=data["locale"].getLocalizedValue(value.getNames())'}}]]
            - [setName, ['attribute_product_brand']]
            - [setParent, ['attribute_localized_fallback']]
        tags:
            - { name: layout.block_type, alias: attribute_product_brand }

    oro_product.block_type.product_sticker:
        parent: oro_layout.block_type.abstract_configurable
        calls:
            -
                - setOptionsConfig
                -
                    -
                        mode: {default: 'badge'}
                        position: {default: 'end-start'}
                        stickers: {default: []}
            - [setName, ['product_sticker']]
        tags:
            - { name: layout.block_type, alias: product_sticker }

    # Component added back for theme layout BC from version 5.0
    oro_product.block_type.directions:
        parent: oro_layout.block_type.abstract_configurable
        calls:
            - [setOptionsConfig, [{method: {required: true, default: 'GET'}}]]
            - [setName, ['quick_add_form_directions']]
            - [setParent, ['container']]
        tags:
            - { name: layout.block_type, alias: quick_add_form_directions }

    oro_product.block_type.product_list_item_image:
        parent: oro_layout.block_type.abstract_configurable
        calls:
            - [setOptionsConfig, [{product_image_size: {default: 'product_large'}}]]
            - [setName, ['product_list_item_image']]
            - [setParent, ['container']]
        tags:
            - { name: layout.block_type, alias: product_list_item_image }

    oro_product.block_type.product_listing_view:
        parent: oro_layout.block_type.abstract_configurable
        calls:
            - [setOptionsConfig, [{popup_gallery: {default: true}}]]
            - [setName, ['product_listing_view']]
            - [setParent, ['container']]
        tags:
            - { name: layout.block_type, alias: product_listing_view }
