services:
    _defaults:
        tags:
            - { name: oro_message_queue.topic }

    Oro\Bundle\ProductBundle\Async\Topic\ReindexProductCollectionBySegmentTopic: ~
    Oro\Bundle\ProductBundle\Async\Topic\ReindexRequestItemProductsByRelatedJobIdTopic: ~
