operations:
    oro_web_catalog_edit_content_tree:
        label: oro.webcatalog.button.webcatalog.edit_content_tree.label
        routes: [oro_web_catalog_view]
        acl_resource: oro_web_catalog_update
        datagrids:
            - web-catalog-grid
        order: 10
        button_options:
            icon: fa-sitemap
        actions:
            - '@redirect':
                route: 'oro_content_node_update_root'
                route_parameters:
                    id: $.data.id
    oro_web_catalog_delete_content_node:
        extends: DELETE
        acl_resource: oro_web_catalog_update
        replace:
            - for_all_datagrids
            - for_all_entities
            - preconditions
        preactions:
            -   '@assign_value':  [$.buttonTooltip, null]
            -   '@assign_value':  [$.enabled, true]
            -   '@call_service_method':
                    conditions:
                        '@not_blank': $.data
                    parameters:
                        service: oro_web_catalog.content_node.deletion_resolver
                        method: checkOnNotDeletableContentNodeUsingTree
                        method_parameters: [$.data]
                        attribute: $.notDeletableContentNodeContext
            -   '@assign_value':
                    conditions:
                        '@not_blank': $.notDeletableContentNodeContext
                    parameters:
                        '@assign_value':  [$.enabled, false]
            -   '@call_service_method':
                    conditions:
                        '@not_blank': $.notDeletableContentNodeContext
                    parameters:
                        service: oro_web_catalog.content_node.deletion_resolver
                        method: getDeletionWarningMessage
                        method_parameters: [ $.notDeletableContentNodeContext ]
                        attribute: $.buttonTooltip
        preconditions:
            '@not_blank': $.data
        routes:
            - 'oro_content_node_update'
            - 'oro_content_node_update_root'
        actions:
            - '@redirect':
                route: 'oro_content_node_update_root'
                route_parameters:
                    id: $.data.webCatalog.id
        frontend_options:
            title: $.buttonTooltip
        enabled: $.enabled
