api:
    entities:
        Oro\Bundle\WebCatalogBundle\Entity\WebCatalog:
            documentation_resource: '@OroWebCatalogBundle/Resources/doc/api/web_catalog.md'
            fields:
                tree:
                    data_type: objects
                    property_path: _
            actions:
                get_list: false
                create: false
                update: false
                delete: false
                delete_list: false
