dynamic-imports:
    jstree:
        - orowebcatalog/js/app/views/content-node-from-webcatalog-form-view
        - orowebcatalog/js/app/views/web-catalog-tree-view
    orowebcatalog:
        - orowebcatalog/js/app/components/content-variant-collection-component
        - orowebcatalog/js/app/views/content-node-from-webcatalog-view
        - orowebcatalog/js/app/views/default-variant-collection-view
        - orowebcatalog/js/app/views/variant-body-view
        - orowebcatalog/js/app/views/variants-collection-view
