search:
    Oro\Bundle\WebCatalogBundle\Entity\WebCatalog:
        alias:                          oro_web_catalog
        route:
            name:                       oro_web_catalog_view
            parameters:
                id:                     id
        search_template:                '@OroWebCatalog/WebCatalog/searchResult.html.twig'
        fields:
            -
                name:                   name
                target_type:            text
                target_fields:          [name]
            -
                name:                   description
                target_type:            text
                target_fields:          [description]
