services:
    _defaults:
        public: true

    _instanceof:
        Symfony\Contracts\Service\ServiceSubscriberInterface:
            tags:
                - { name: container.service_subscriber }

        Symfony\Bundle\FrameworkBundle\Controller\AbstractController:
            calls:
                - ['setContainer', ['@Psr\Container\ContainerInterface']]

    Oro\Bundle\ShoppingListBundle\Controller\ShoppingListController: ~

    Oro\Bundle\ShoppingListBundle\Controller\Frontend\ShoppingListController: ~

    Oro\Bundle\ShoppingListBundle\Controller\Frontend\MatrixGridOrderController: ~

    Oro\Bundle\ShoppingListBundle\Controller\Frontend\AjaxLineItemController:
        tags:
            - { name: container.service_subscriber, id: oro_shopping_list.handler.shopping_list_line_item, key: Oro\Bundle\ShoppingListBundle\Handler\ShoppingListLineItemHandler }

    Oro\Bundle\ShoppingListBundle\Controller\Frontend\AjaxProductKitLineItemController:
        arguments:
            - '@oro_shopping_list.product_kit.checker.product_kit_availability_checker'
            - '@oro_shopping_list.manager.current_shopping_list'
            - '@oro_shopping_list.manager.shopping_list'
            - '@oro_shopping_list.product_kit.factory.product_kit_line_item'
            - '@oro_pricing.subtotal_processor.provider.subtotal_line_item_not_priced'
            - '@oro_product.model.product_line_items_holder_factory'
            - '@doctrine'
            - '@validator'

    Oro\Bundle\ShoppingListBundle\Controller\Frontend\AjaxMassActionController: ~
