services:
    oro_shopping_list.form.type.shopping_list:
        class: 'Oro\Bundle\ShoppingListBundle\Form\Type\ShoppingListType'
        tags:
            - { name: form.type, alias: oro_shopping_list_type }
        calls:
            - [setDataClass, ['Oro\Bundle\ShoppingListBundle\Entity\ShoppingList']]

    oro_shopping_list.form.type.line_item:
        class: 'Oro\Bundle\ShoppingListBundle\Form\Type\LineItemType'
        calls:
            - [setDataClass, ['Oro\Bundle\ShoppingListBundle\Entity\LineItem']]
        tags:
            - { name: form.type, alias: oro_shopping_list_line_item }

    oro_shopping_list.form.type.frontend_line_item_widget:
        class: 'Oro\Bundle\ShoppingListBundle\Form\Type\FrontendLineItemWidgetType'
        arguments:
            - '@translator'
            - '@oro_shopping_list.manager.current_shopping_list'
        tags:
            - { name: form.type, alias: oro_shopping_list_frontend_line_item_widget }
