services:
    oro_shopping_list.mass_action.add_products:
        class: 'Oro\Bundle\ShoppingListBundle\Datagrid\Extension\MassAction\AddProductsMassAction'
        arguments:
            - '@oro_entity_merge.metadata.registry'
            - '@translator'
        shared: false
        tags:
            - { name: oro_datagrid.extension.mass_action.type, type: addproducts }

    oro_shopping_list.mass_action.add_products_handler:
        class: 'Oro\Bundle\ShoppingListBundle\Datagrid\Extension\MassAction\AddProductsMassActionHandler'
        public: true
        arguments:
            - '@oro_shopping_list.handler.shopping_list_line_item'
            - '@oro_shopping_list.service.message_generator'
            - '@doctrine'
            - '@oro_shopping_list.data_provider.product_shopping_lists'
            - '@oro_security.acl_helper'

    oro_shopping_list.mass_action.move_products:
        class: 'Oro\Bundle\ShoppingListBundle\Datagrid\Extension\MassAction\MoveProductsMassAction'
        arguments:
            - '@oro_entity_merge.metadata.registry'
            - '@translator'
        shared: false
        tags:
            - { name: oro_datagrid.extension.mass_action.type, type: moveproducts }

    oro_shopping_list.mass_action.move_products_handler:
        class: 'Oro\Bundle\ShoppingListBundle\Datagrid\Extension\MassAction\MoveProductsMassActionHandler'
        public: true
        arguments:
            - '@doctrine'
            - '@translator'
            - '@security.authorization_checker'
            - '@request_stack'
            - '@oro_shopping_list.manager.shopping_list'
            - '@oro_shopping_list.manager.shopping_list_total'
