services:
    oro_shopping_list.tests.entity_name_resolver.data_loader:
        class: Oro\Bundle\ShoppingListBundle\Tests\Functional\Environment\TestEntityNameResolverDataLoader
        decorates: oro_entity.tests.entity_name_resolver.data_loader
        arguments:
            - '@.inner'
