Oro\Bundle\ShoppingListBundle\Entity\LineItem:
    constraints:
        - Oro\Bundle\ShoppingListBundle\Validator\Constraints\LineItem:
            groups: [update]
        - Oro\Bundle\ProductBundle\Validator\Constraints\QuantityUnitPrecision:
            path: quantity
            groups: [Default, create, update, add_product]
    properties:
        product:
            - NotBlank:
                groups: [create, update, add_product]
        quantity:
            - Oro\Bundle\ValidationBundle\Validator\Constraints\Decimal:
                groups: [create, update, add_product]
            - Oro\Bundle\ValidationBundle\Validator\Constraints\GreaterThanZero:
                value: 0
                groups: [create, update, add_product]
            - NotBlank:
                groups: [create, update, add_product]
        unit:
            - NotBlank:
                groups: [create, update, add_product]
        shoppingList:
            - NotBlank:
                groups: [create, update]
        notes:
            - Length:
                max: 2048
                groups: [Default, create, update, add_product]

Oro\Bundle\ShoppingListBundle\Entity\ShoppingList:
    properties:
        label:
            - NotBlank: ~
            - Length:
                max: 255
        totals:
            - Valid: ~
        notes:
            - Length:
                max: 2048
        lineItems:
            - Valid: ~

Oro\Bundle\ShoppingListBundle\Entity\ShoppingListTotal:
    properties:
        subtotalValue:
            - Type:
                type: numeric
                groups: [create, update, add_product]
            - Oro\Bundle\ValidationBundle\Validator\Constraints\NumericRange:
                minMessage: 'oro.shoppinglist.subtotal.min.error.label'
                maxMessage: 'oro.shoppinglist.subtotal.max.error.label'

Oro\Bundle\ShoppingListBundle\Model\MatrixCollectionColumn:
    constraints:
        - Oro\Bundle\ShoppingListBundle\Validator\Constraints\MatrixCollectionColumn: ~
    properties:
        quantity:
            - Oro\Bundle\ValidationBundle\Validator\Constraints\Decimal: ~
            - Oro\Bundle\ValidationBundle\Validator\Constraints\GreaterThanZero: ~
