api:
    entities:
        Oro\Bundle\CatalogBundle\Entity\CategoryTitle:
            documentation_resource: '@OroCatalogBundle/Resources/doc/api/category_title.md'
            actions:
                create: false
                update: false
                delete: false
                delete_list: false

        Oro\Bundle\CatalogBundle\Entity\CategoryShortDescription:
            documentation_resource: '@OroCatalogBundle/Resources/doc/api/category_short_description.md'
            actions:
                create: false
                update: false
                delete: false
                delete_list: false

        Oro\Bundle\CatalogBundle\Entity\CategoryLongDescription:
            documentation_resource: '@OroCatalogBundle/Resources/doc/api/category_long_description.md'
            actions:
                create: false
                update: false
                delete: false
                delete_list: false

        Oro\Bundle\CatalogBundle\Entity\Category:
            documentation_resource: '@OroCatalogBundle/Resources/doc/api/category.md'
            fields:
                denormalizedDefaultTitle:
                    exclude: true
            actions:
                create: false
                update: false
                delete: false
                delete_list: false

        Oro\Bundle\ProductBundle\Entity\Product:
            documentation_resource: '@OroCatalogBundle/Resources/doc/api/product.md'
            fields:
                category: ~
                category_sort_order: ~

        Oro\Bundle\EntityBundle\Entity\EntityFieldFallbackValue:
            documentation_resource: '@OroCatalogBundle/Resources/doc/api/entity_field_fallback_value.md'
