features:
    frontend_master_catalog:
        label: oro.catalog.feature.frontend_master_catalog.label
        description: oro.catalog.feature.frontend_master_catalog.description
        allow_if_all_abstain: true

    all_products_page:
        label: oro.catalog.feature.all_products_page.label
        description: oro.catalog.feature.all_products_page.description
        toggle: oro_catalog.all_products_page_enabled
        routes:
            - oro_catalog_frontend_product_allproducts

    manage_master_catalog:
        label: oro.catalog.feature.master_catalog.manage.label
        description: oro.catalog.feature.master_catalog.manage.description
        allow_if_all_abstain: true
        routes:
            - oro_catalog_category_index
            - oro_catalog_category_create
            - oro_catalog_category_update
            - oro_catalog_category_move_form
            - oro_catalog_category_tree_widget
            - oro_catalog_category_get_changed_slugs
            - oro_catalog_category_move
        entities:
            - Oro\Bundle\CatalogBundle\Entity\Category
            - Oro\Bundle\CatalogBundle\Entity\CategoryTitle
            - Oro\Bundle\CatalogBundle\Entity\CategoryShortDescription
            - Oro\Bundle\CatalogBundle\Entity\CategoryLongDescription
        operations:
            - oro_catalog_category_delete
        navigation_items:
            - application_menu.products_tab.master_catalog
