placeholders:
    placeholders:
        product_index_sidebar:
            items:
                product_sidebar_category_selector:
                    order: 100
        oro_product_step_two_info:
            items:
                product_step_two_category_info:
                    order: 100
    items:
        product_sidebar_category_selector:
            action: Oro\Bundle\CatalogBundle\Controller\ProductController::sidebarAction
            acl: oro_catalog_category_view
        product_step_two_category_info:
            template: '@@OroCatalog/Product/category_info.html.twig'
