search:
    Oro\Bundle\CatalogBundle\Entity\Category:
        alias:                          oro_category
        route:
            name:                       oro_catalog_category_update
            parameters:
                id:                     id
        search_template:                '@OroCatalog/Category/searchResult.html.twig'
        acl_permission:                 'EDIT'
        fields:
            -
                name:                   defaultTitle
                target_type:            text
                target_fields:          [defaultTitle]
            -
                name: titles
                relation_type: many-to-many
                relation_fields:
                    -
                        name: string
                        target_type: text
                        target_fields: [titles]
