system_configuration:
    groups:
        catalog:
            title: oro.catalog.system_configuration.groups.catalog.title
        special_pages:
            title: oro.catalog.system_configuration.groups.special_pages.title
            icon: fa-file-excel-o
        all_products:
            title: oro.catalog.system_configuration.groups.all_products.title

    fields:
        oro_catalog.category_direct_url_prefix:
            data_type: string
            type: Oro\Bundle\RedirectBundle\Form\Type\SluggableEntityPrefixType
            search_type: text
            options:
                label: oro.catalog.system_configuration.fields.category_direct_url_prefix.label
                data_transformer: oro_redirect.form.transformer.prefix_with_redirect_to_string
                required: false
                constraints:
                    - Oro\Bundle\ValidationBundle\Validator\Constraints\UrlSafe: ~

        oro_catalog.all_products_page_enabled:
            data_type: boolean
            type: Oro\Bundle\ConfigBundle\Form\Type\ConfigCheckbox
            priority: 10
            options:
                label: oro.catalog.system_configuration.fields.all_products_page_enabled.label
                tooltip: oro.catalog.system_configuration.fields.all_products_page_enabled.tooltip

        oro_catalog.category_image_placeholder:
            data_type: string
            type: 'Oro\Bundle\ConfigBundle\Form\Type\ConfigFileType'
            priority: 40
            options:
                label: oro.catalog.system_configuration.fields.category_image_placeholder.label
                tooltip: oro.catalog.system_configuration.fields.category_image_placeholder.tooltip
                required: false
                fileConstraints:
                    - Oro\Bundle\AttachmentBundle\Validator\Constraints\Image: ~

    tree:
        system_configuration:
            platform:
                children:
                    websites:
                        children:
                            routing:
                                children:
                                    oro_redirect_direct_urls:
                                        children:
                                            - oro_catalog.category_direct_url_prefix
            commerce:
                children:
                    catalog:
                        priority: 900
                        children:
                          special_pages:
                              children:
                                  all_products:
                                      children:
                                          - oro_catalog.all_products_page_enabled
                    design:
                        children:
                            theme:
                                children:
                                    theme_settings:
                                        children:
                                            - oro_catalog.category_image_placeholder
