Oro\Bundle\ProductBundle\Entity\Product:
    fields:
        -
            name: category_id
            type: integer
        -
            name: category_path
            type: text
            fulltext: false
        -
            name: category_title_LOCALIZATION_ID
            type: text
            fulltext: false
        -
            name: category_paths.CATEGORY_PATH
            type: integer
