services:
    oro_tax.tests.alias.transformer.tax_value:
        alias: oro_tax.transformer.tax_value
        public: true

    oro_tax.tests.alias.tax_codes.cache:
        alias: oro_tax.tax_codes.cache
        public: true

    oro_tax.tests.alias.taxation_provider.cache:
        alias: oro_tax.taxation_provider.cache
        public: true

    oro_tax.tests.entity_name_resolver.data_loader:
        class: Oro\Bundle\TaxBundle\Tests\Functional\Environment\TestEntityNameResolverDataLoader
        decorates: oro_entity.tests.entity_name_resolver.data_loader
        arguments:
            - '@.inner'
