services:
    # Attribute types (fields)
    oro_website_search.searchable_attribute_type.bigint:
        class: Oro\Bundle\WebsiteSearchBundle\Attribute\Type\IntegerSearchableAttributeType
        decorates: oro_entity_config.attribute_type.bigint
        arguments:
            - '@.inner'

    oro_website_search.searchable_attribute_type.boolean:
        class: Oro\Bundle\WebsiteSearchBundle\Attribute\Type\BooleanSearchableAttributeType
        decorates: oro_entity_config.attribute_type.boolean
        arguments:
            - '@.inner'

    oro_website_search.searchable_attribute_type.money:
        class: Oro\Bundle\WebsiteSearchBundle\Attribute\Type\DecimalSearchableAttributeType
        decorates: oro_entity_config.attribute_type.money
        arguments:
            - '@.inner'

    oro_website_search.searchable_attribute_type.date:
        class: Oro\Bundle\WebsiteSearchBundle\Attribute\Type\DateSearchableAttributeType
        decorates: oro_entity_config.attribute_type.date
        arguments:
            - '@.inner'

    oro_website_search.searchable_attribute_type.datetime:
        class: Oro\Bundle\WebsiteSearchBundle\Attribute\Type\DateSearchableAttributeType
        decorates: oro_entity_config.attribute_type.datetime
        arguments:
            - '@.inner'

    oro_website_search.searchable_attribute_type.decimal:
        class: Oro\Bundle\WebsiteSearchBundle\Attribute\Type\DecimalSearchableAttributeType
        decorates: oro_entity_config.attribute_type.decimal
        arguments:
            - '@.inner'

    oro_website_search.searchable_attribute_type.file:
        class: Oro\Bundle\WebsiteSearchBundle\Attribute\Type\FileSearchableAttributeType
        decorates: oro_entity_config.attribute_type.file
        arguments:
            - '@.inner'

    oro_website_search.searchable_attribute_type.float:
        class: Oro\Bundle\WebsiteSearchBundle\Attribute\Type\DecimalSearchableAttributeType
        decorates: oro_entity_config.attribute_type.float
        arguments:
            - '@.inner'

    oro_website_search.searchable_attribute_type.wysiwyg:
        class: Oro\Bundle\WebsiteSearchBundle\Attribute\Type\WYSIWYGSearchableAttributeType
        decorates: oro_cms.attribute_type.wysiwyg
        arguments:
            - '@.inner'

    oro_website_search.searchable_attribute_type.image:
        class: Oro\Bundle\WebsiteSearchBundle\Attribute\Type\FileSearchableAttributeType
        decorates: oro_entity_config.attribute_type.image
        arguments:
            - '@.inner'

    oro_website_search.searchable_attribute_type.multifile:
        class: Oro\Bundle\WebsiteSearchBundle\Attribute\Type\FileSearchableAttributeType
        decorates: oro_entity_config.attribute_type.multifile
        arguments:
            - '@.inner'

    oro_website_search.searchable_attribute_type.multiimage:
        class: Oro\Bundle\WebsiteSearchBundle\Attribute\Type\FileSearchableAttributeType
        decorates: oro_entity_config.attribute_type.multiimage
        arguments:
            - '@.inner'

    oro_website_search.searchable_attribute_type.integer:
        class: Oro\Bundle\WebsiteSearchBundle\Attribute\Type\IntegerSearchableAttributeType
        decorates: oro_entity_config.attribute_type.integer
        arguments:
            - '@.inner'

    oro_website_search.searchable_attribute_type.multienum:
        class: Oro\Bundle\WebsiteSearchBundle\Attribute\Type\MultiEnumSearchableAttributeType
        decorates: oro_entity_config.attribute_type.multienum
        arguments:
            - '@.inner'

    oro_website_search.searchable_attribute_type.percent:
        class: Oro\Bundle\WebsiteSearchBundle\Attribute\Type\PercentSearchableAttributeType
        decorates: oro_entity_config.attribute_type.percent
        arguments:
            - '@.inner'

    oro_website_search.searchable_attribute_type.enum:
        class: Oro\Bundle\WebsiteSearchBundle\Attribute\Type\EnumSearchableAttributeType
        decorates: oro_entity_config.attribute_type.enum
        arguments:
            - '@.inner'

    oro_website_search.searchable_attribute_type.smallint:
        class: Oro\Bundle\WebsiteSearchBundle\Attribute\Type\IntegerSearchableAttributeType
        decorates: oro_entity_config.attribute_type.smallint
        arguments:
            - '@.inner'

    oro_website_search.searchable_attribute_type.string:
        class: Oro\Bundle\WebsiteSearchBundle\Attribute\Type\StringSearchableAttributeType
        decorates: oro_entity_config.attribute_type.string
        arguments:
            - '@.inner'

    oro_website_search.searchable_attribute_type.text:
        class: Oro\Bundle\WebsiteSearchBundle\Attribute\Type\TextSearchableAttributeType
        decorates: oro_entity_config.attribute_type.text
        arguments:
            - '@.inner'

    # Attribute types (relations)
    oro_website_search.searchable_attribute_type.manytomany:
        class: Oro\Bundle\WebsiteSearchBundle\Attribute\Type\ManyToManySearchableAttributeType
        decorates: oro_entity_config.attribute_type.manytomany
        arguments:
            - '@.inner'

    oro_website_search.searchable_attribute_type.manytoone:
        class: Oro\Bundle\WebsiteSearchBundle\Attribute\Type\ManyToOneSearchableAttributeType
        decorates: oro_entity_config.attribute_type.manytoone
        arguments:
            - '@.inner'

    oro_website_search.searchable_attribute_type.onetomany:
        class: Oro\Bundle\WebsiteSearchBundle\Attribute\Type\OneToManySearchableAttributeType
        decorates: oro_entity_config.attribute_type.onetomany
        arguments:
            - '@.inner'
