services:
    Oro\Bundle\WebsiteSearchBundle\Command\ReindexCommand:
        public: false
        class: Oro\Bundle\WebsiteSearchBundle\Command\ReindexCommand
        tags:
            - { name: console.command }
