services:
    oro_website_search.api.filter_factory.website_search_query:
        class: Oro\Bundle\SearchBundle\Api\Filter\SearchQueryFilterFactory
        arguments:
            - '@oro_website_search.provider.search_mapping'
            - '@oro_website_search.api.field_resolver_factory.website_search_query_filter'
            - '@oro_website_search.api.search_query_criteria_visitor'

    oro_website_search.api.filter_factory.website_search_aggregation:
        class: Oro\Bundle\SearchBundle\Api\Filter\SearchAggregationFilterFactory
        arguments:
            - '@oro_website_search.api.field_resolver_factory.website_search_aggregation_filter'

    oro_website_search.api.field_resolver_factory.website_search_query_filter:
        class: Oro\Bundle\WebsiteSearchBundle\Api\SearchFieldResolverFactory
        arguments:
            - '@oro_website_search.provider.search_mapping'

    oro_website_search.api.field_resolver_factory.website_search_aggregation_filter:
        class: Oro\Bundle\SearchBundle\Api\Filter\SearchFieldResolverFactory
        arguments:
            - '@oro_website_search.provider.search_mapping'

    oro_website_search.api.search_query_criteria_visitor:
        class: Oro\Bundle\WebsiteSearchBundle\Api\SearchQueryCriteriaVisitor
