Oro\Bundle\WebsiteSearchBundle\SearchResult\Entity\SearchResultHistory:
    properties:
        searchTerm:
            - NotBlank: ~
            - Length:
                min: 1
                max: 1024
        normalizedSearchTermHash:
            - NotBlank: ~
            - Length:
                min: 32
                max: 32
        resultType:
            - NotBlank: ~
            - Length:
                max: 32
        resultsCount:
            - NotBlank: ~
            - Type: integer
        website:
            - NotBlank: ~
