features:
    quick_order_form:
        label: oro.product.feature.quick_order_form.label
        description: oro.product.feature.quick_order_form.description
        toggle: oro_product.enable_quick_order_form
        routes:
            - 'oro_product_frontend_quick_add'
            - 'oro_product_frontend_quick_add_import'
            - 'oro_product_frontend_quick_add_copy_paste'
            - 'oro_product_frontend_quick_add_validation_result'
        configuration:
            - 'guest_quick_order_form'

    guest_quick_order:
        label: oro.product.feature.guest_quick_order_form.label
        description: oro.product.feature.quick_order_form.description
        strategy: affirmative

    guest_quick_order_form:
        label: oro.product.feature.guest_quick_order_form.label
        description: oro.product.feature.quick_order_form.description
        toggle: oro_product.guest_quick_order_form
        routes:
            - 'oro_product_frontend_quick_add'
            - 'oro_product_frontend_quick_add_import'
            - 'oro_product_frontend_quick_add_copy_paste'
            - 'oro_product_frontend_quick_add_validation_result'
        dependencies:
            - 'guest_quick_order'
        strategy: affirmative

    limit_filters_sorters_on_product_listing:
        label: oro.product.feature.limit_filters_sorters_on_product_listing.label
        description: oro.product.feature.limit_filters_sorters_on_product_listing.description
        toggle: oro_product.limit_filters_sorters_on_product_listing
