placeholders:
    placeholders:
        js_modules_config:
            items:
                oro_product_js_modules_config:
                    order: 100
        oro_product_quick_add_buttons:
            items:
                quick_add_actions_buttons: ~
        oro_product_related_items_view: ~
        oro_product_related_items_edit: ~
        oro_product_related_products_buttons:
            items:
                oro_product_select_related_products_button: ~
        oro_product_upsell_products_buttons:
            items:
                oro_product_select_upsell_products_button: ~
        oro_product_upsell_products_view: ~
        oro_product_upsell_products_edit: ~

    items:
        quick_add_actions_buttons:
            template: '@@OroAction/Widget/buttons.html.twig'
        oro_product_select_related_products_button:
            template: '@@OroProduct/Product/selectRelatedProductsButton.html.twig'
        oro_product_select_upsell_products_button:
            template: '@@OroProduct/Product/selectUpsellProductsButton.html.twig'
        oro_product_js_modules_config:
            template: '@@OroProduct/Product/js_modules_config.html.twig'
            applicable: "@oro_layout.helper->isTemplateRequest()"
            data: '%oro_product.sku.regex_pattern%'
