api:
    entities:
        Oro\Bundle\PaymentTermBundle\Entity\PaymentTerm:
            # this entity does not have own API resource,
            # but it should be defined to correct work of "paymentTerm" property
            # of the order API resource
            actions: false
