datagrids:
    payment-terms-grid:
        acl_resource: oro_payment_term_view
        extended_entity_name: 'Oro\Bundle\PaymentTermBundle\Entity\PaymentTerm'
        options:
            entityHint: oro.paymentterm.entity_plural_label
            entity_pagination: true
        source:
            type:         orm
            query:
                select:
                    - paymentTerm.id
                    - paymentTerm.label
                from:
                    - { table: 'Oro\Bundle\PaymentTermBundle\Entity\PaymentTerm', alias: paymentTerm }
        columns:
            label:
                label: oro.paymentterm.label.label
        properties:
            id: ~
            view_link:
                type:  url
                route: oro_payment_term_view
                params:
                    - id
            update_link:
                type: url
                route: oro_payment_term_update
                params: [ id ]
        sorters:
            columns:
                label:
                    data_name: paymentTerm.label
            default:
                label: ASC
        filters:
            columns:
                label:
                    type:      string
                    data_name: paymentTerm.label
        actions:
            view:
                type:          navigate
                label:         oro.grid.action.view
                link:          view_link
                icon:          eye
                acl_resource:  oro_payment_term_view
                rowAction:     true
            update:
                type:          navigate
                label:         oro.grid.action.update
                link:          update_link
                icon:          edit
                acl_resource:  oro_payment_term_update

    payment-terms-select-grid:
        acl_resource: oro_payment_term_view
        options:
            entityHint: oro.paymentterm.entity_plural_label
        source:
            type:         orm
            query:
                select:
                    - paymentTerm.id
                    - paymentTerm.label
                from:
                    - { table: 'Oro\Bundle\PaymentTermBundle\Entity\PaymentTerm', alias: paymentTerm }
        columns:
            label:
                label: oro.paymentterm.label.label
        properties:
            id: ~
        sorters:
            columns:
                label:
                    data_name: paymentTerm.label
            default:
                label: ASC
        filters:
            columns:
                label:
                    type:      string
                    data_name: paymentTerm.label
