services:
    _defaults:
        public: true

    Oro\Bundle\PaymentBundle\Controller\PaymentMethodsConfigsRuleController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }

    # Frontend controllers

    Oro\Bundle\PaymentBundle\Controller\Frontend\CallbackController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
