api:
    entity_aliases:
        Extend\Entity\EV_Variant_Field_Code:
            alias:        testapivariantfieldcode
            plural_alias: testapivariantfieldcodes

    entities:
        Extend\Entity\EV_Multienum_Code:
            exclude: true
