search:
    Oro\Bundle\TestFrameworkBundle\Entity\TestProduct:
        label:           Test Search Product
        alias:           oro_test_product
        search_template: '@OroSearch/Test/searchResult.html.twig'
        route:
            name: oro_search_results
        fields:
            -
                name: name
                target_type: text
