dynamic-imports:
    oropayment:
        - oropaypal/js/app/components/authorized-credit-card-component
        - oropaypal/js/app/components/credit-card-component
        - oropaypal/js/app/components/payflow-express-checkout-component
