workflows:
    b2b_flow_checkout_single_page:
        steps:
            checkout:
                order: 10
                allowed_transitions:
                    - save_state
                    - create_order
                    - purchase
                    - finish_checkout
                    - payment_error
                    - start_from_quickorderform

            order_created:
                order: 20
                is_final: true
