datagrids:
    customer-category-visibility-grid:
        source:
            type:              orm
            query:
                select:
                    - customer.id
                    - customer.name
                    - visibilityAlias
                from:
                    - { table: 'Oro\Bundle\CustomerBundle\Entity\Customer', alias: customer }
                join:
                    left:
                        - { join: 'Oro\Bundle\ScopeBundle\Entity\Scope', alias: scope, conditionType: WITH, condition: 'scope.customer = customer' }
                        - { join: 'Oro\Bundle\VisibilityBundle\Entity\Visibility\CustomerCategoryVisibility', alias: visibilityAlias, conditionType: WITH, condition: 'visibilityAlias.category = :target_entity_id and visibilityAlias.scope = scope' }
            bind_parameters:
                - target_entity_id
        columns:
            name:
                label: oro.customer.customer.name.label
            visibility:
                label: oro.visibility.customercategoryvisibility.entity_label
                frontend_type: select
                editable: true
        sorters:
            columns:
                name:
                    data_name: customer.name
                visibility:
                    data_name: visibilityAlias.visibility
            default:
                name: ASC
        filters:
            columns:
                name:
                    type:      string
                    data_name: customer.name
                visibility:
                    type: visibility_choice
                    visibilityEntityClass: 'Oro\Bundle\VisibilityBundle\Entity\Visibility\CustomerCategoryVisibility'
                    targetEntityClass: 'Oro\Bundle\CatalogBundle\Entity\Category'
                    data_name: visibilityAlias.visibility
                    options:
                        field_options:
                            multiple: true
        options:
            scopeAttr: 'customer'
            visibilityEntityClass: 'Oro\Bundle\VisibilityBundle\Entity\Visibility\CustomerCategoryVisibility'
            targetEntityClass: 'Oro\Bundle\CatalogBundle\Entity\Category'
            cellSelection:
                dataField: id
                columnName:
                    - visibility
                selector: '#customer-category-visibility-changeset'
        properties:
            id: ~

    customer-group-category-visibility-grid:
        source:
            type:              orm
            query:
                select:
                    - customerGroup.id
                    - customerGroup.name
                    - visibilityAlias
                from:
                    - { table: 'Oro\Bundle\CustomerBundle\Entity\CustomerGroup', alias: customerGroup }
                join:
                    left:
                        - { join: 'Oro\Bundle\ScopeBundle\Entity\Scope', alias: scope, conditionType: WITH, condition: 'scope.customerGroup = customerGroup' }
                        - { join: 'Oro\Bundle\VisibilityBundle\Entity\Visibility\CustomerGroupCategoryVisibility', alias: visibilityAlias, conditionType: WITH, condition: 'visibilityAlias.category = :target_entity_id and visibilityAlias.scope = scope' }
            bind_parameters:
                - target_entity_id
        columns:
            name:
                label: oro.customer.customer.name.label
            visibility:
                label: oro.visibility.customergroupcategoryvisibility.entity_label
                frontend_type: select
                editable: true
        sorters:
            columns:
                name:
                    data_name: customerGroup.name
                visibility:
                    data_name: visibilityAlias.visibility
            default:
                name: ASC
        filters:
            columns:
                name:
                    type:      string
                    data_name: customerGroup.name
                visibility:
                    type: visibility_choice
                    visibilityEntityClass: 'Oro\Bundle\VisibilityBundle\Entity\Visibility\CustomerGroupCategoryVisibility'
                    targetEntityClass: 'Oro\Bundle\CatalogBundle\Entity\Category'
                    data_name: visibilityAlias.visibility
                    options:
                        field_options:
                            multiple: true
        options:
            scopeAttr: 'customerGroup'
            visibilityEntityClass: 'Oro\Bundle\VisibilityBundle\Entity\Visibility\CustomerGroupCategoryVisibility'
            targetEntityClass: 'Oro\Bundle\CatalogBundle\Entity\Category'
            cellSelection:
                dataField: id
                columnName:
                    - visibility
                selector: '#customergroup-category-visibility-changeset'
        properties:
            id: ~

    customer-product-visibility-grid:
        scope: website
        source:
            type:              orm
            query:
                select:
                    - customer.id
                    - customer.name
                    - visibilityAlias
                from:
                    - { table: 'Oro\Bundle\CustomerBundle\Entity\Customer', alias: customer }
                join:
                    left:
                        - { join: 'Oro\Bundle\ScopeBundle\Entity\Scope', alias: scope, conditionType: WITH, condition: 'scope.customer = customer' }
                        - { join: 'Oro\Bundle\VisibilityBundle\Entity\Visibility\CustomerProductVisibility', alias: visibilityAlias, conditionType: WITH, condition: 'visibilityAlias.product = :target_entity_id and visibilityAlias.scope = scope' }
            bind_parameters:
                - target_entity_id
        columns:
            name:
                label: oro.customer.customer.name.label
            visibility:
                label: oro.visibility.customerproductvisibility.entity_label
                frontend_type: select
                editable: true
        sorters:
            columns:
                name:
                    data_name: customer.name
                visibility:
                    data_name: visibilityAlias.visibility
            default:
                name: ASC
        filters:
            columns:
                name:
                    type:      string
                    data_name: customer.name
                visibility:
                    type: visibility_choice
                    visibilityEntityClass: 'Oro\Bundle\VisibilityBundle\Entity\Visibility\CustomerProductVisibility'
                    targetEntityClass: 'Oro\Bundle\ProductBundle\Entity\Product'
                    data_name: visibilityAlias.visibility
                    options:
                        field_options:
                            multiple: true
        options:
            scopeAttr: 'customer'
            visibilityEntityClass: 'Oro\Bundle\VisibilityBundle\Entity\Visibility\CustomerProductVisibility'
            targetEntityClass: 'Oro\Bundle\ProductBundle\Entity\Product'
            cellSelection:
                dataField: id
                columnName:
                    - visibility
                selector: '#customer-product-visibility-changeset'
        properties:
            id: ~

    customer-group-product-visibility-grid:
        scope: website
        source:
            type:              orm
            query:
                select:
                    - customerGroup.id
                    - customerGroup.name
                from:
                    - { table: 'Oro\Bundle\CustomerBundle\Entity\CustomerGroup', alias: customerGroup }
                join:
                    left:
                        - { join: 'Oro\Bundle\ScopeBundle\Entity\Scope', alias: scope, conditionType: WITH, condition: 'scope.customerGroup = customerGroup' }
                        - { join: 'Oro\Bundle\VisibilityBundle\Entity\Visibility\CustomerGroupProductVisibility', alias: visibilityAlias, conditionType: WITH, condition: 'visibilityAlias.product = :target_entity_id and visibilityAlias.scope = scope' }
            bind_parameters:
                - target_entity_id
        columns:
            name:
                label: oro.customer.customer.name.label
            visibility:
                label: oro.visibility.customergroupproductvisibility.entity_label
                frontend_type: select
                editable: true
        sorters:
            columns:
                name:
                    data_name: customerGroup.name
                visibility:
                    data_name: visibilityAlias.visibility
            default:
                name: ASC
        filters:
            columns:
                name:
                    type:      string
                    data_name: customerGroup.name
                visibility:
                    type: visibility_choice
                    data_name: visibilityAlias.visibility
                    visibilityEntityClass: 'Oro\Bundle\VisibilityBundle\Entity\Visibility\CustomerGroupProductVisibility'
                    targetEntityClass: 'Oro\Bundle\ProductBundle\Entity\Product'
                    options:
                        field_options:
                            multiple: true
        options:
            scopeAttr: 'customerGroup'
            visibilityEntityClass: 'Oro\Bundle\VisibilityBundle\Entity\Visibility\CustomerGroupProductVisibility'
            targetEntityClass: 'Oro\Bundle\ProductBundle\Entity\Product'
            cellSelection:
                dataField: id
                columnName:
                    - visibility
                selector: '#customergroup-product-visibility-changeset'
        properties:
            id: ~
