services:
    _defaults:
        public: true

    Oro\Bundle\ShippingBundle\Controller\Api\Rest\ShippingMethodsConfigsRuleController:
        calls:
            - [ 'setContainer', [ '@Psr\Container\ContainerInterface' ] ]
        tags:
            - { name: container.service_subscriber }
            - { name: container.service_subscriber, id: oro_shipping.shipping_rule.manager.api, key: Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager }
