services:
    oro_shipping.shipping_method_provider:
        class: 'Oro\Bundle\ShippingBundle\Method\CompositeShippingMethodProvider'
        arguments:
            - !tagged_iterator oro_shipping_method_provider

    oro_shipping.formatter.shipping_method_label:
        class: 'Oro\Bundle\ShippingBundle\Formatter\ShippingMethodLabelFormatter'
        arguments:
            - "@oro_shipping.shipping_method_provider"

    oro_shipping.translator.shipping_method_label:
        class: 'Oro\Bundle\ShippingBundle\Translator\ShippingMethodLabelTranslator'
        arguments:
            - "@oro_shipping.formatter.shipping_method_label"
            - "@translator.default"

    oro_shipping.tracking_aware_shipping_methods_provider:
        class: 'Oro\Bundle\ShippingBundle\Method\TrackingAwareShippingMethodsProvider'
        arguments:
            - '@oro_shipping.shipping_method_provider'
