operations:
    DELETE:
        exclude_entities:
            - Oro\Bundle\CMSBundle\Entity\LoginPage
        exclude_datagrids:
            - cms-login-page-grid
            - cms-content-block-grid
    UPDATE:
        exclude_datagrids:
            - cms-content-block-grid

    oro_cms_content_block_delete:
        extends: DELETE
        for_all_entities: false
        for_all_datagrids: false
        replace:
            - datagrids
            - preconditions
            - exclude_datagrids
        datagrids:
            - cms-content-block-grid
        preconditions:
            '@and':
                - '@not_blank': $.data
                - '@or':
                    - '@blank': $.requestRoute
                    - '@and':
                        - '@not_blank': $.routes[name]
                - '@or':
                    - '@not_blank': $.routes[name]
                    - '@not_blank': $.gridName
    oro_cms_content_block_update:
        extends: UPDATE
        for_all_entities: false
        for_all_datagrids: false
        replace:
            - datagrids
            - preconditions
            - exclude_datagrids
        datagrids:
            - cms-content-block-grid
        preconditions:
            '@and':
                - '@not_blank': $.data
                - '@not_blank': $.routes[update]
                - '@or':
                    - '@blank': $.requestRoute
                    - '@and':
                        - '@not_blank': $.routes[name]

    oro_cms_content_template_clone:
        extends: CLONE
        for_all_entities: false
        for_all_datagrids: false
        entities:
            - Oro\Bundle\CMSBundle\Entity\ContentTemplate
        routes:
            - oro_cms_content_template_view
        replace:
            - datagrids
        datagrids:
            - content-template-grid
        acl_resource: oro_cms_content_template_create
        actions:
            - '@assign_value': [$.clone.enabled, false]
            - '@trans':
                attribute: $.suffix
                id: 'oro.cms.contenttemplate.cloned_name_suffix'
            - '@add_string_suffix':
                  attribute: $.clone.name
                  maxLength: 255
                  string: $name
                  stringSuffix: $.suffix
            - '@copy_tagging':
                source: $.data
                destination: $.clone
            - '@tree':
                conditions:
                    '@not_empty': [ $.data.previewImage ]
                actions:
                    - '@call_service_method':
                        service: oro_attachment.file_manager
                        method: cloneFileEntity
                        method_parameters: [ $.data.previewImage ]
                        attribute: $.clone.previewImage
            - '@flush_entity': $.clone

    CMS_CREATE_DRAFT:
        extends: CREATE_DRAFT
        entities:
            - Oro\Bundle\CMSBundle\Entity\Page

    CMS_PUBLISH_DRAFT:
        extends: PUBLISH_DRAFT
        entities:
            - Oro\Bundle\CMSBundle\Entity\Page
        datagrids:
            - cms-page-drafts-grid

    CMS_DUPLICATE_DRAFT:
        extends: DUPLICATE_DRAFT
        entities:
            - Oro\Bundle\CMSBundle\Entity\Page
        datagrids:
            - cms-page-drafts-grid

    CMS_UPDATE_DRAFT:
        extends: UPDATE_DRAFT
        datagrids:
            - cms-page-drafts-grid

    CMS_DELETE_DRAFT:
        extends: DELETE_DRAFT
        datagrids:
            - cms-page-drafts-grid
