navigation:
    menu_config:
        items:
            marketing_tab:
                label:           'oro.cms.menu.marketing_tab.label'
                uri:             '#'
                position:        400
                extras:
                    icon:        fa-book

            page_list:
                label:           'oro.cms.page.entity_plural_label'
                route:           'oro_cms_page_index'
                position:        100
                extras:
                    routes:      ['/^oro_cms_page/']
                    description: 'oro.cms.menu.page_list.description'

            content_template_list:
                label:           'oro.cms.contenttemplate.entity_plural_label'
                route:           'oro_cms_content_template_index'
                position:        101
                extras:
                    routes:      ['/^oro_cms_content_template/']
                    description: 'oro.cms.menu.content_template.description'

            content_block_list:
                label:           'oro.cms.contentblock.entity_plural_label'
                route:           'oro_cms_content_block_index'
                position:        102
                extras:
                    routes:      ['/^oro_cms_content_block/']
                    description: 'oro.cms.menu.contentblock_list.description'

            login_page_list:
                label:           'oro.cms.loginpage.entity_plural_label'
                route:           'oro_cms_loginpage_index'
                position:        103
                extras:
                    routes:      ['/^oro_cms_loginpage/']
                    description: 'oro.cms.menu.loginpage_list.description'

            content_widget_list:
                label:           'oro.cms.contentwidget.entity_plural_label'
                route:           'oro_cms_content_widget_index'
                position:        104
                extras:
                    routes:      ['/^oro_cms_content_widget/']

            shortcut_page_list:
                label:           'oro.cms.page.entity_plural_label'
                route:           'oro_cms_page_index'
                extras:
                    description: 'oro.cms.menu.shortcut_page_list.description'
        tree:
            application_menu:
                children:
                    marketing_tab:
                        children:
                            page_list: ~
                            content_block_list: ~
                            content_widget_list: ~
                            login_page_list: ~
                            digital_asset_list: ~
                            content_template_list: ~
            shortcuts:
                children:
                    shortcut_pages_list: ~

    titles:
        oro_cms_page_index:  ~
        oro_cms_page_view:   '%title%'
        oro_cms_page_update: '%title% - oro.ui.edit'
        oro_cms_page_create: 'oro.ui.create_entity'

        oro_cms_loginpage_index:  ~
        oro_cms_loginpage_view:   '%title%'
        oro_cms_loginpage_update: 'oro.ui.edit'
        oro_cms_loginpage_create: 'oro.ui.create'

        oro_cms_frontend_page_view: '%title%'

        oro_cms_content_block_index:  ~
        oro_cms_content_block_view: '%title%'
        oro_cms_content_block_update: '%title% - oro.ui.edit'
        oro_cms_content_block_create: 'oro.ui.create'

        oro_cms_content_widget_index:  ~
        oro_cms_content_widget_view: '%title%'
        oro_cms_content_widget_update: '%title% - oro.ui.edit'
        oro_cms_content_widget_create: 'oro.ui.create'
