oro_cms_page:
    resource:     "@OroCMSBundle/Controller/PageController.php"
    type:         annotation
    prefix:       /cms/page

oro_cms_frontend_page:
    resource:     "@OroCMSBundle/Controller/Frontend/PageController.php"
    type:         annotation
    prefix:       /cms/page
    options:
        frontend: true

oro_cms_login_page:
    resource:     "@OroCMSBundle/Controller/LoginPageController.php"
    type:         annotation
    prefix:       /cms/login-page

oro_cms_content_block:
    resource:     "@OroCMSBundle/Controller/ContentBlockController.php"
    type:         annotation
    prefix:       /cms/content-block

oro_cms_content_widget:
    resource:     "@OroCMSBundle/Controller/ContentWidgetController.php"
    type:         annotation
    prefix:       /cms/content-widget

oro_cms_wysiwyg_content:
    resource:     "@OroCMSBundle/Controller/WysiwygContentController.php"
    type:         annotation
    prefix:       /cms/wysiwyg/content

oro_cms_content_template:
    resource:     "@OroCMSBundle/Controller/ContentTemplateController.php"
    type:         annotation
    prefix:       /cms/content-template
