operations:
    oro_fixed_product_integration_price_attribute_delete:
        extends: DELETE
        substitute_operation: DELETE
        for_all_entities: false
        for_all_datagrids: false
        replace:
            - actions
        datagrids:
            - pricing-price-attribute-price-list-grid
        entities:
            - Oro\Bundle\PricingBundle\Entity\PriceAttributePriceList
        actions:
            - '@call_service_method':
                    attribute: $.result
                    service: oro_fixed_product_shipping.handler.shipping_cost_attribute_delete_handler
                    method: isAttributeFixed
                    method_parameters: [$.data]
            - '@flash_message':
                    conditions:
                        '@equal': [$.result, true]
                    message: oro.fixed_product.action.delete.fixed.message
                    type: 'error'
            - '@tree':
                conditions:
                    '@equal': [$.result, false]
                actions:
                    - '@run_action_group':
                        action_group: DELETE
                        parameters_mapping:
                            data: $.data
                    - '@flash_message':
                        message: oro.action.delete_message
                        type: 'success'
                        message_parameters:
                            entityLabel: $.entityLabel
                    - '@refresh_grid':
                        conditions:
                            '@and':
                                - '@empty': $.routes[name]
                                - '@not_empty': $.gridName
                        parameters: [$.gridName]

    oro_integration_deactivate:
        preactions:
            - '@assign_constant_value':
                attribute: $.fixedProductType
                value: Oro\Bundle\FixedProductShippingBundle\Integration\FixedProductChannelType::TYPE
        preconditions:
            '@and':
                - '@not_equal': [$type, $.fixedProductType]

    oro_integration_delete:
        preactions:
            - '@assign_constant_value':
                attribute: $.fixedProductType
                value: Oro\Bundle\FixedProductShippingBundle\Integration\FixedProductChannelType::TYPE
        preconditions:
            '@and':
                - '@not_equal': [$type, $.fixedProductType]

    oro_fixed_product_integration_deactivate:
        extends: oro_integration_deactivate
        for_all_entities: false
        for_all_datagrids: false
        replace:
            - preactions
            - preconditions
            - frontend_options
        preactions:
            - '@assign_constant_value':
                attribute: $.fixedProductType
                value: Oro\Bundle\FixedProductShippingBundle\Integration\FixedProductChannelType::TYPE
            - '@call_service_method':
                attribute: $.actionAllowed
                service: oro_integration.utils.edit_mode
                method: isSwitchEnableAllowed
                method_parameters: [$.data.editMode]
            - '@call_service_method':
                attribute: $.methodIdentifier
                service: oro_fixed_product_shipping.method.identifier_generator.method
                method: generateIdentifier
                method_parameters: [$.data]
            - '@call_service_method':
                attribute: $.linkGrid
                service: oro_shipping.helper.filtered_datagrid_route
                method: generate
                method_parameters:  [{'methodConfigs': $.methodIdentifier}]
        preconditions:
            '@and':
                - '@shipping_method_has_enabled_shipping_rules':
                    parameters:
                        method_identifier: $.methodIdentifier
                - '@equal': [$type, $.fixedProductType]
                - '@equal': [$.actionAllowed, true]
                - '@equal': [$.data.enabled, true]
        frontend_options:
            confirmation:
                title: oro.shipping.integration.deactivate.title
                okText: oro.shipping.integration.deactivate.button.okText
                message: oro.shipping.integration.deactivate.message
                message_parameters:
                    linkGrid: $.linkGrid
                component: oroui/js/standart-confirmation

    oro_fixed_product_integration_deactivate_without_rules:
        extends: oro_fixed_product_integration_deactivate
        for_all_entities: false
        for_all_datagrids: false
        replace:
            - preconditions
            - frontend_options
        preconditions:
            '@and':
                - '@not':
                    - '@shipping_method_has_enabled_shipping_rules':
                        parameters:
                            method_identifier: $.methodIdentifier
                - '@equal': [$type, $.fixedProductType]
                - '@equal': [$.actionAllowed, true]
                - '@equal': [$.data.enabled, true]
        frontend_options: ~

    oro_fixed_product_integration_delete:
        extends: oro_integration_delete
        for_all_entities: false
        for_all_datagrids: false
        replace:
            - preactions
            - preconditions
            - frontend_options
        preactions:
            - '@assign_constant_value':
                attribute: $.fixedProductType
                value: Oro\Bundle\FixedProductShippingBundle\Integration\FixedProductChannelType::TYPE
            - '@call_service_method':
                service: oro_integration.utils.edit_mode
                method: isEditAllowed
                method_parameters: [$.data.editMode]
                attribute: $.actionAllowed
            - '@call_service_method':
                attribute: $.methodIdentifier
                service: oro_fixed_product_shipping.method.identifier_generator.method
                method: generateIdentifier
                method_parameters: [$.data]
            - '@call_service_method':
                attribute: $.linkGrid
                service: oro_shipping.helper.filtered_datagrid_route
                method: generate
                method_parameters:  [{'methodConfigs': $.methodIdentifier}]
        preconditions:
            '@and':
                - '@shipping_method_has_shipping_rules':
                    parameters:
                        method_identifier: $.methodIdentifier
                - '@equal': [$type, $.fixedProductType]
                - '@equal': [$.actionAllowed, true]
        frontend_options:
            confirmation:
                title: oro.shipping.integration.delete.title
                okText: oro.shipping.integration.delete.button.okText
                message: oro.shipping.integration.delete.message
                message_parameters:
                    linkGrid: $.linkGrid
                component: oroui/js/standart-confirmation

    oro_fixed_product_integration_delete_without_rules:
        extends: oro_fixed_product_integration_delete
        for_all_entities: false
        for_all_datagrids: false
        replace:
            - preconditions
            - frontend_options
        preconditions:
            '@and':
                - '@not':
                    - '@shipping_method_has_shipping_rules':
                        parameters:
                            method_identifier: $.methodIdentifier
                - '@equal': [$type, $.fixedProductType]
                - '@equal': [$.actionAllowed, true]
        frontend_options:
            title: oro.action.delete_entity
            confirmation:
                title: oro.action.delete_entity
                message: oro.action.delete_confirm
                message_parameters:
                    entityLabel: $name
                component: oroui/js/delete-confirmation
