services:
    _defaults:
        public: true

    Oro\Bundle\SaleBundle\Controller\Frontend\QuoteController:
        calls:
            - [setContainer, ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: 'container.service_subscriber' }

    Oro\Bundle\SaleBundle\Controller\Frontend\AjaxQuoteProductController:
        calls:
            - [ setContainer, [ '@Psr\Container\ContainerInterface' ] ]
        tags:
            - { name: 'container.service_subscriber' }

    Oro\Bundle\SaleBundle\Controller\QuoteController:
        calls:
            - [setContainer, ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: 'container.service_subscriber' }

    Oro\Bundle\SaleBundle\Controller\AjaxQuoteController:
        calls:
            - [setContainer, ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: 'container.service_subscriber' }
