entity_config:
    slug:
        # You can find out more about attributes in the documentation: https://doc.oroinc.com/backend/configuration/annotation/config/#slug
        entity:
            items:
                source:
                    options:
                        indexed: true
