system_configuration:
    groups:
        oro_redirect_direct_urls:
            title: oro.redirect.system_configuration.groups.direct_urls.label
        oro_redirect_canonical_urls:
            title: oro.redirect.system_configuration.groups.canonical_urls.label

    fields:
        oro_redirect.enable_direct_url:
            data_type: boolean
            type: Oro\Bundle\ConfigBundle\Form\Type\ConfigCheckbox
            priority: 500
            options:
                label: oro.redirect.system_configuration.fields.enable_direct_url.label
                required: false

        oro_redirect.use_localized_canonical:
            data_type: boolean
            type: Oro\Bundle\ConfigBundle\Form\Type\ConfigCheckbox
            priority: 100
            options:
                label: oro.redirect.system_configuration.fields.use_localized_canonical.label
                tooltip: oro.redirect.system_configuration.fields.use_localized_canonical.tooltip
                required: false

        oro_redirect.canonical_url_type:
            data_type: string
            type: 'Symfony\Component\Form\Extension\Core\Type\ChoiceType'
            search_type: choice
            priority: 300
            options:
                label: oro.redirect.system_configuration.fields.canonical_url_type.label
                required: true
                constraints:
                    - NotBlank: ~
                choices:
                    oro.redirect.system_configuration.fields.canonical_url_type.choice.system.label: system
                    oro.redirect.system_configuration.fields.canonical_url_type.choice.direct.label: direct

        oro_redirect.redirect_generation_strategy:
            data_type: string
            type: 'Symfony\Component\Form\Extension\Core\Type\ChoiceType'
            search_type: choice
            priority: 200
            options:
                label: oro.redirect.system_configuration.fields.redirect_generation_strategy.label
                required: true
                constraints:
                    - NotBlank: ~
                choices:
                    oro.redirect.system_configuration.fields.redirect_generation_strategy.choice.ask.label: ask
                    oro.redirect.system_configuration.fields.redirect_generation_strategy.choice.always.label: always
                    oro.redirect.system_configuration.fields.redirect_generation_strategy.choice.never.label: never

        oro_redirect.canonical_url_security_type:
            data_type: string
            type: 'Symfony\Component\Form\Extension\Core\Type\ChoiceType'
            search_type: choice
            priority: 200
            options:
                label: oro.redirect.system_configuration.fields.canonical_url_security_type.label
                required: true
                constraints:
                    - NotBlank: ~
                choices:
                    oro.redirect.system_configuration.fields.canonical_url_security_type.choice.insecure.label: insecure
                    oro.redirect.system_configuration.fields.canonical_url_security_type.choice.secure.label: secure

    tree:
        system_configuration:
            platform:
                children:
                    websites:
                        children:
                            routing:
                                children:
                                    websites_routing_general:
                                        children:
                                            - oro_redirect.redirect_generation_strategy
                                    oro_redirect_direct_urls:
                                        children:
                                            - oro_redirect.enable_direct_url
                                    oro_redirect_canonical_urls:
                                        children:
                                            - oro_redirect.canonical_url_type
                                            - oro_redirect.canonical_url_security_type
                                            - oro_redirect.use_localized_canonical
