services:
    _defaults:
        public: true

    Oro\Bundle\WebCatalogBundle\Controller\WebCatalogController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }

    Oro\Bundle\WebCatalogBundle\Controller\ContentNodeController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
