datagrids:
    base-quote-grid:
        acl_resource: oro_sale_quote_view
        extended_entity_name: 'Oro\Bundle\SaleBundle\Entity\Quote'
        options:
            entityHint: oro.sale.quote.entity_plural_label
            entity_pagination: true
        source:
            type:         orm
            query:
                select:
                    - quote.id
                    - quote.qid
                    - CONCAT(quoteOwner.firstName, ' ', quoteOwner.lastName) as ownerName
                    - quote.poNumber
                    - quote.shipUntil
                    - quote.createdAt
                    - quote.updatedAt
                    - quote.validUntil
                    - quote.expired
                from:
                    - { table: 'Oro\Bundle\SaleBundle\Entity\Quote', alias: quote }
                join:
                    left:
                        - { join: quote.owner, alias: quoteOwner }
        columns:
            qid:
                label:         oro.sale.quote.qid.label
            ownerName:
                label:         oro.sale.quote.owner.label
            expired:
                label:         oro.sale.quote.expired.label
                frontend_type: boolean
            validUntil:
                label:         oro.sale.quote.valid_until.label
                frontend_type: datetime
            poNumber:
                label:         oro.sale.quote.po_number.label
            shipUntil:
                label:         oro.sale.quote.ship_until.label
                frontend_type: date
            createdAt:
                label:         oro.ui.created_at
                frontend_type: datetime
            updatedAt:
                label:         oro.ui.updated_at
                frontend_type: datetime
        properties:
            id: ~
            view_link:
                type:  url
                route: oro_sale_quote_view
                params: [ id ]
        sorters:
            columns:
                qid:
                    data_name: quote.qid
                ownerName:
                    data_name: ownerName
                expired:
                    data_name: quote.expired
                poNumber:
                    data_name: quote.poNumber
                shipUntil:
                    data_name: quote.shipUntil
                createdAt:
                    data_name: quote.createdAt
                updatedAt:
                    data_name: quote.updatedAt
                validUntil:
                    data_name: quote.validUntil
            default:
                qid: ASC
        actions:
            view:
                type:          navigate
                label:         oro.grid.action.view
                link:          view_link
                icon:          eye
                acl_resource:  oro_sale_quote_view
                rowAction:     true

    customer-view-quote-grid:
        extends: base-quote-grid
        source:
            query:
                select:
                    - CONCAT(quoteCustomerUser.firstName, ' ', quoteCustomerUser.lastName) as customerUserName
                where:
                    or:
                        - quoteCustomerUser.customer = :customer_id
                        - quote.customer = :customer_id
                join:
                    left:
                        - { join: quote.customerUser, alias: quoteCustomerUser }
            bind_parameters:
                - customer_id
        sorters:
            columns:
                customerUserName:
                    data_name: customerUserName
        columns:
            customerUserName:
                label:         oro.sale.quote.customer_user.label
                order:         1
        filters:
            columns:
                qid:
                    type:      string
                    data_name: quote.qid
                customerUserName:
                    type:      string
                    data_name: customerUserName
                ownerName:
                    type:      string
                    data_name: ownerName
                expired:
                    type:      boolean
                    data_name: quote.expired
                validUntil:
                    type:      datetime
                    data_name: quote.validUntil
                poNumber:
                    type:      string
                    data_name: quote.poNumber
                shipUntil:
                    type:      date
                    data_name: quote.shipUntil
                createdAt:
                    type:      datetime
                    data_name: quote.createdAt
                updatedAt:
                    type:      datetime
                    data_name: quote.updatedAt

    customer-user-view-quote-grid:
        extends: base-quote-grid
        source:
            query:
                where:
                    and:
                        - quote.customerUser = :customer_user_id
            bind_parameters:
                - customer_user_id
        filters:
            columns:
                qid:
                    type:      string
                    data_name: quote.qid
                ownerName:
                    type:      string
                    data_name: ownerName
                expired:
                    type:      boolean
                    data_name: quote.expired
                validUntil:
                    type:      datetime
                    data_name: quote.validUntil
                poNumber:
                    type:      string
                    data_name: quote.poNumber
                shipUntil:
                    type:      date
                    data_name: quote.shipUntil
                createdAt:
                    type:      datetime
                    data_name: quote.createdAt
                updatedAt:
                    type:      datetime
                    data_name: quote.updatedAt

    quotes-grid:
        extends: base-quote-grid
        source:
            query:
                select:
                    - CONCAT(quoteCustomerUser.firstName, ' ', quoteCustomerUser.lastName) as customerUserName
                    - quoteCustomer.name as customerName
                    - internalStatus.name as internalStatusName
                    - internalStatus.id as internalStatusId
                    - customerStatus.name as customerStatusName
                    - customerStatus.id as customerStatusId
                join:
                    left:
                        - { join: quote.customerUser, alias: quoteCustomerUser }
                        - { join: quote.customer, alias: quoteCustomer }
                        - { join: quote.internal_status, alias: internalStatus }
                        - { join: quote.customer_status, alias: customerStatus }
            hints:
                - HINT_TRANSLATABLE
        columns:
            customerUserName:
                label: oro.sale.quote.customer_user.label
                order: 2
            customerName:
                label: oro.sale.quote.customer.label
                order: 3
            internalStatusName:
                label: oro.sale.quote.internal_status.label
                order: 4
            customerStatusName:
                label: oro.sale.quote.customer_status.label
                order: 5
        sorters:
            columns:
                customerUserName:
                    data_name: customerUserName
                customerName:
                    data_name: customerName
                internalStatusName:
                    data_name: internalStatusName
                customerStatusName:
                    data_name: customerStatusName
        filters:
            columns:
                qid:
                    type:      string
                    data_name: quote.qid
                ownerName:
                    type:      string
                    data_name: ownerName
                customerUserName:
                    type:      string
                    data_name: customerUserName
                customerName:
                    type:      string
                    data_name: customerName
                internalStatusName:
                    type:      enum
                    data_name: internalStatusId
                    enum_code: quote_internal_status
                customerStatusName:
                    type:      enum
                    data_name: customerStatusId
                    enum_code: quote_customer_status
                expired:
                    type:      boolean
                    data_name: quote.expired
                validUntil:
                    type:      datetime
                    data_name: quote.validUntil
                poNumber:
                    type:      string
                    data_name: quote.poNumber
                shipUntil:
                    type:      date
                    data_name: quote.shipUntil
                createdAt:
                    type:      datetime
                    data_name: quote.createdAt
                updatedAt:
                    type:      datetime
                    data_name: quote.updatedAt
