oro_entity:
    virtual_fields:
        Oro\Bundle\SaleBundle\Entity\Quote:
            contactInformation:
                query:
                    select:
                        expr: user.email
                        return_type: string
                    join:
                        left:
                            - { join: entity.customerUser, alias: user }

    virtual_relations:
        Oro\Bundle\OrderBundle\Entity\Order:
            quote:
                relation_type: oneToOne
                related_entity_name: Oro\Bundle\SaleBundle\Entity\Quote
                label: oro.sale.quote.entity_label
                query:
                    join:
                        left:
                            - { join: Oro\Bundle\SaleBundle\Entity\Quote, alias: quote, conditionType: WITH, condition: "entity.sourceEntityClass = 'Oro\\Bundle\\SaleBundle\\Entity\\Quote' AND entity.sourceEntityId = quote.id" }
