services:
    _defaults:
        public: true

    Oro\Bundle\InventoryBundle\Controller\InventoryLevelController:
        calls:
            - [setContainer, ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
            - { name: container.service_subscriber, id: oro_inventory.manager.inventory_manager, key: Oro\Bundle\InventoryBundle\Inventory\InventoryManager }
