services:
    oro_catalog.form.type.category:
        class: 'Oro\Bundle\CatalogBundle\Form\Type\CategoryType'
        arguments:
            - '@router'
        calls:
            - [setDataClass, ['Oro\Bundle\CatalogBundle\Entity\Category']]
            - [setProductClass, ['Oro\Bundle\ProductBundle\Entity\Product']]
        tags:
            - { name: form.type, alias: oro_catalog_category }

    oro_catalog.form.type.category_default_product_options:
        class: 'Oro\Bundle\CatalogBundle\Form\Type\CategoryDefaultProductOptionsType'
        calls:
            - [setDataClass, ['Oro\Bundle\CatalogBundle\Entity\CategoryDefaultProductOptions']]
        tags:
            - { name: form.type, alias: oro_catalog_category_default_product_options }

    oro_catalog.form.type.category_unit_precision:
        class: 'Oro\Bundle\CatalogBundle\Form\Type\CategoryUnitPrecisionType'
        arguments:
            - '@oro_catalog.visibility.default_product_options'
        calls:
            - [setDataClass, ['Oro\Bundle\CatalogBundle\Model\CategoryUnitPrecision']]
        tags:
            - { name: form.type, alias: oro_catalog_category_unit_precision }

    oro_catalog.form.type.category_tree:
        class: 'Oro\Bundle\CatalogBundle\Form\Type\CategoryTreeType'
        arguments:
            - '@oro_catalog.category_tree_handler'
        tags:
            - { name: form.type, alias: oro_catalog_category_tree }

    oro_catalog.form.extension.product_type:
        class: 'Oro\Bundle\CatalogBundle\Form\Extension\ProductFormExtension'
        arguments:
            - '@doctrine'
            - '@security.authorization_checker'
        tags:
            - { name: form.type_extension, alias: oro_product, extended_type: Oro\Bundle\ProductBundle\Form\Type\ProductType }

    oro_catalog.form.extension.product_step_one_type:
        class: 'Oro\Bundle\CatalogBundle\Form\Extension\ProductStepOneFormExtension'
        arguments:
            - '@oro_catalog.provider.default_product_unit_provider.category'
            - '@security.authorization_checker'
        public: true
        tags:
            - { name: form.type_extension, alias: oro_product_step_one, extended_type: Oro\Bundle\ProductBundle\Form\Type\ProductStepOneType }

    oro_catalog.form.type.category_page_content_variant:
        class: Oro\Bundle\CatalogBundle\Form\Type\CategoryPageVariantType
        tags:
            - { name: form.type, alias: oro_catalog_category_page_variant }
