services:
    oro_catalog.tests.entity_name_resolver.data_loader:
        class: Oro\Bundle\CatalogBundle\Tests\Functional\Environment\TestEntityNameResolverDataLoader
        decorates: oro_entity.tests.entity_name_resolver.data_loader
        arguments:
            - '@.inner'
