api:
    entities:
        Oro\Bundle\OrderBundle\Entity\OrderLineItem:
            documentation_resource: '@OroPromotionBundle/Resources/doc/api_frontend/order_line_item.md'
            fields:
                rowTotalDiscountAmount:
                    data_type: money
                    property_path: _
                    form_options:
                        mapped: false
                rowTotalAfterDiscountIncludingTax:
                    data_type: money
                    property_path: _
                    form_options:
                        mapped: false
                rowTotalAfterDiscountExcludingTax:
                    data_type: money
                    property_path: _
                    form_options:
                        mapped: false
                rowTotalAfterDiscount:
                    data_type: money
                    property_path: _
                    depends_on: [value, quantity]
                    form_options:
                        mapped: false
