doctrine:
    orm:
        dql:
            string_functions:
                decode: Oro\Bundle\PromotionBundle\ORM\Query\AST\Functions\String\Decode

oro_entity:
    entity_name_representation:
        Oro\Bundle\PromotionBundle\Entity\Coupon:
            full: [ code ]
            short: [ code ]
