placeholders:
    placeholders:
        render_discount_information:
            items:
                order_discount_information: ~
                line_item_discount_information: ~
                buy_x_get_y_discount_information: ~
                shipping_discount_information: ~
        order_edit_section_applied_discounts_after:
            items:
                order_edit_section_applied_discounts_after_item_with_taxes: ~
                order_edit_section_applied_discounts_after_item_without_taxes: ~

    items:
        order_discount_information:
            applicable: "@oro_promotion.placeholder.discount_information_placeholder_filter->isApplicable($entity$, order)"
            template: '@@OroPromotion/Promotion/discountPlaceholders/order.html.twig'
        line_item_discount_information:
            applicable: "@oro_promotion.placeholder.discount_information_placeholder_filter->isApplicable($entity$, line_item)"
            template: '@@OroPromotion/Promotion/discountPlaceholders/lineItem.html.twig'
        buy_x_get_y_discount_information:
            applicable: "@oro_promotion.placeholder.discount_information_placeholder_filter->isApplicable($entity$, buy_x_get_y)"
            template: '@@OroPromotion/Promotion/discountPlaceholders/buyXGetY.html.twig'
        shipping_discount_information:
            applicable: "@oro_promotion.placeholder.discount_information_placeholder_filter->isApplicable($entity$, shipping)"
            template: '@@OroPromotion/Promotion/discountPlaceholders/shipping.html.twig'
        order_edit_section_applied_discounts_after_item_with_taxes:
            applicable: "@oro_tax.provider.taxation_settings_provider->isEnabled()"
            template: '@@OroPromotion/Order/Form/applied_discounts_with_taxes.html.twig'
        order_edit_section_applied_discounts_after_item_without_taxes:
            applicable: "@oro_tax.provider.taxation_settings_provider->isDisabled()"
            template: '@@OroPromotion/Order/Form/applied_discounts_without_taxes.html.twig'
