services:
    oro_cms.layout.block_type.login_page_logo:
        parent: oro_layout.block_type.abstract_configurable_container
        calls:
            - [setName, ['login_page_logo']]
            - [setOptionsConfig, [{logo: {required: true}}]]
        tags:
            - { name: layout.block_type, alias: login_page_logo }

    oro_cms.layout.block_type.login_page:
        parent: oro_layout.block_type.abstract_configurable_container
        calls:
            - [setName, ['login_page']]
            - [setOptionsConfig, [{loginPage: ~}]]
        tags:
             - { name: layout.block_type, alias: login_page }

    oro_cms.layout.block_type.content_block:
        parent: oro_layout.block_type.abstract_configurable
        calls:
            - [setName, ['content_block']]
            -
                - setOptionsConfig
                -
                    -
                        alias: {required: true}
                        contentBlock: {default: '=data["content_block"].getContentBlockView(alias)'}
                        visible: {default: '=data["content_block"].getContentBlockView(alias)!==null'}
        tags:
             - { name: layout.block_type, alias: content_block }

    oro_cms.layout.block_type.content_widget_root:
        parent: oro_layout.block_type.abstract_configurable_container
        calls:
            - [setName, ['content_widget_root']]
        tags:
            - { name: layout.block_type, alias: content_widget_root }

    oro_cms.layout.block_type.content_widget_default_template:
        parent: oro_layout.block_type.abstract_configurable
        calls:
            - [setName, ['content_widget_default_template']]
            -
                - setOptionsConfig
                -
                    -
                        defaultTemplate: {required: true}
        tags:
            - { name: layout.block_type, alias: content_widget_default_template }

    oro_cms.layout.block_type.wysiwyg_content:
        parent: oro_layout.block_type.abstract_configurable
        calls:
            - [setName, ['wysiwyg_content']]
            - [setParent, ['container']]
            - [setOptionsConfig, [{content: {required: true}, contentStyle: {required: false}}]]
        tags:
             - { name: layout.block_type, alias: wysiwyg_content }

    oro_cms.layout.block_type.attribute_wysiwyg:
        parent: oro_entity_config.block_type.attribute_file
        calls:
            - [setName, ['attribute_wysiwyg']]
            - [setParent, ['attribute_text']]
            - [setOptionsConfig, [{styles: {default: '=data["property_accessor"].getValue(entity, fieldName ~ "_style")'}}]]
        tags:
             - { name: layout.block_type, alias: attribute_wysiwyg }
