services:
    Oro\Bundle\CMSBundle\Tests\Functional\ContentWidget\Stub\StubContentWidgetType:
        tags:
            - {name: 'oro_cms.content_widget.type'}

    oro_cms.tests.event_listener.wysiwyg_field_twig_listener:
        alias: oro_cms.event_listener.wysiwyg_field_twig_listener
        public: true
