placeholders:
    placeholders:
        oro_pricing_totals:
            items:
                oro_pricing_tax_totals: ~
        order_edit_section_unitPriceIncludingTax_after: { items: { order_edit_section_unitPriceIncludingTax_after_item: ~ } }
        order_edit_section_unitPriceExcludingTax_after: { items: { order_edit_section_unitPriceExcludingTax_after_item: ~ } }
        order_edit_section_unitPriceTaxAmount_after: { items: { order_edit_section_unitPriceTaxAmount_after_item: ~ } }
        order_edit_section_rowTotalIncludingTax_after: { items: { order_edit_section_rowTotalIncludingTax_after_item: ~ } }
        order_edit_section_rowTotalExcludingTax_after: { items: { order_edit_section_rowTotalExcludingTax_after_item: ~ } }
        order_edit_section_rowTotalTaxAmount_after: { items: { order_edit_section_rowTotalTaxAmount_after_item: ~ } }
        order_edit_section_taxes_after: { items: { order_edit_section_taxes_after_item: ~ } }

        scripts_before:
            items:
                order_taxes_totals_template: ~
                order_taxes_item_taxes_template: ~
                order_taxes_item_items_template: ~

    items:
        oro_pricing_tax_totals:
            template: '@@OroTax/placeholder.html.twig'
            applicable: "@oro_tax.provider.taxation_settings_provider->isEnabled()"
        order_edit_section_unitPriceIncludingTax_after_item:
            template: '@@OroTax/Order/Form/unitPriceIncludingTax.html.twig'
            applicable: "@oro_tax.provider.taxation_settings_provider->isEnabled()"
        order_edit_section_unitPriceExcludingTax_after_item:
            template: '@@OroTax/Order/Form/unitPriceExcludingTax.html.twig'
            applicable: "@oro_tax.provider.taxation_settings_provider->isEnabled()"
        order_edit_section_unitPriceTaxAmount_after_item:
            template: '@@OroTax/Order/Form/unitPriceTaxAmount.html.twig'
            applicable: "@oro_tax.provider.taxation_settings_provider->isEnabled()"
        order_edit_section_rowTotalIncludingTax_after_item:
            template: '@@OroTax/Order/Form/rowTotalIncludingTax.html.twig'
            applicable: "@oro_tax.provider.taxation_settings_provider->isEnabled()"
        order_edit_section_rowTotalExcludingTax_after_item:
            template: '@@OroTax/Order/Form/rowTotalExcludingTax.html.twig'
            applicable: "@oro_tax.provider.taxation_settings_provider->isEnabled()"
        order_edit_section_rowTotalTaxAmount_after_item:
            template: '@@OroTax/Order/Form/rowTotalTaxAmount.html.twig'
            applicable: "@oro_tax.provider.taxation_settings_provider->isEnabled()"
        order_edit_section_taxes_after_item:
            template: '@@OroTax/Order/Form/taxes.html.twig'
            applicable: "@oro_tax.provider.taxation_settings_provider->isEnabled()"
        order_taxes_totals_template:
            template: '@@OroTax/Js/totals.html.twig'
            applicable:
                - "@oro_tax.provider.taxation_settings_provider->isEnabled()"
                - "@oro_layout.helper->isTemplateRequest()"
        order_taxes_item_taxes_template:
            template: '@@OroTax/Js/item_taxes.html.twig'
            applicable:
                - "@oro_tax.provider.taxation_settings_provider->isEnabled()"
                - "@oro_layout.helper->isTemplateRequest()"
        order_taxes_item_items_template:
            template: '@@OroTax/Js/item_items.html.twig'
            applicable:
                - "@oro_tax.provider.taxation_settings_provider->isEnabled()"
                - "@oro_layout.helper->isTemplateRequest()"
