search:
    Oro\Bundle\TaxBundle\Entity\Tax:
        alias:                          oro_tax
        route:
            name:                       oro_tax_view
            parameters:
                id:                     id
        search_template:                '@OroTax/Tax/searchResult.html.twig'
        fields:
            -
                name:                   code
                target_type:            text
                target_fields:          [code]
            -
                name:                   description
                target_type:            text
                target_fields:          [description]

    Oro\Bundle\TaxBundle\Entity\ProductTaxCode:
        alias:                          oro_product_tax_code
        route:
            name:                       oro_tax_product_tax_code_view
            parameters:
                id:                     id
        search_template:  '@OroTax/ProductTaxCode/searchResult.html.twig'
        fields:
            -
                name:                   code
                target_type:            text
                target_fields:          [code]
            -
                name:                   description
                target_type:            text
                target_fields:          [description]

    Oro\Bundle\TaxBundle\Entity\CustomerTaxCode:
        alias:                          oro_customer_tax_code
        route:
            name:                       oro_tax_customer_tax_code_view
            parameters:
                id:                     id
        search_template:  '@OroTax/CustomerTaxCode/searchResult.html.twig'
        fields:
            -
                name:                   code
                target_type:            text
                target_fields:          [code]
            -
                name:                   description
                target_type:            text
                target_fields:          [description]

    Oro\Bundle\TaxBundle\Entity\TaxJurisdiction:
        alias:                          oro_tax_jurisdiction
        route:
            name:                       oro_tax_jurisdiction_view
            parameters:
                id:                     id
        search_template:                '@OroTax/TaxJurisdiction/searchResult.html.twig'
        fields:
            -
                name:                   code
                target_type:            text
                target_fields:          [code]
            -
                name:                   description
                target_type:            text
                target_fields:          [description]
