system_configuration:
    groups:
        taxation:
            title: oro.tax.system_configuration.groups.taxation.title
        tax_calculation:
            title: oro.tax.system_configuration.groups.tax_calculation.title
            icon: fa-money
        tax_enable:
            title: oro.tax.system_configuration.groups.tax_enable.title
        tax_provider:
            title: oro.tax.system_configuration.groups.tax_provider.title
        tax_calculator:
            title: oro.tax.system_configuration.groups.tax_calculator.title
        tax_matcher:
            title: oro.tax.system_configuration.groups.tax_matcher.title
        origin_address:
            title: oro.tax.system_configuration.groups.origin_address.title
        tax_digital_products:
            title: oro.tax.system_configuration.groups.tax_digital_products.title
        us_sales_tax:
            title: oro.tax.system_configuration.groups.us_sales_tax.title
            icon: fa-usd
        eu_vat_tax:
            title: oro.tax.system_configuration.groups.eu_vat_tax.title
            icon: fa-eur
        tax_shipping:
            title: oro.tax.system_configuration.groups.shipping.title
            icon: fa-truck
        shipping_tax:
            title: oro.tax.system_configuration.groups.shipping_tax.title
        promotions:
            title: oro.tax.system_configuration.groups.promotions.title

    fields:
        oro_tax.tax_enable:
            data_type: boolean
            type: Oro\Bundle\ConfigBundle\Form\Type\ConfigCheckbox
            options:
                label: oro.tax.system_configuration.fields.tax_enable.label
                required: false

        oro_tax.tax_provider:
            data_type: string
            type: Oro\Bundle\TaxBundle\Form\Type\TaxProviderType
            options:
                label: oro.tax.system_configuration.fields.tax_provider.label
                required: true
                constraints:
                    - NotBlank: ~

        oro_tax.start_calculation_with:
            data_type: string
            type: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            search_type: choice
            options:
                label: oro.tax.system_configuration.fields.start_calculation_with.label
                required: true
                constraints:
                    - NotBlank: ~
                choices:
                    oro.tax.system_configuration.fields.start_calculation_with.unit_price.label: unit_price
                    oro.tax.system_configuration.fields.start_calculation_with.row_total.label: row_total

        oro_tax.start_calculation_on:
            data_type: string
            type: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            search_type: choice
            options:
                label: oro.tax.system_configuration.fields.start_calculation_on.label
                required: true
                constraints:
                    - NotBlank: ~
                choices:
                    oro.tax.system_configuration.fields.start_calculation_on.total.label: total
                    oro.tax.system_configuration.fields.start_calculation_on.item.label: item

        oro_tax.product_prices_include_tax:
            data_type: boolean
            type: Oro\Bundle\ConfigBundle\Form\Type\ConfigCheckbox
            options:
                label: oro.tax.system_configuration.fields.product_prices_include_tax.label
                required: false

        oro_tax.use_as_base_by_default:
            data_type: string
            type: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            search_type: choice
            options:
                label: oro.tax.system_configuration.fields.use_as_base.default.label
                required: true
                constraints:
                    - NotBlank: ~
                choice_translation_domain: messages
                choices:
                    oro.tax.system_configuration.fields.use_as_base.origin.label: origin
                    oro.tax.system_configuration.fields.use_as_base.destination.label: destination

        oro_tax.address_resolver_granularity:
            data_type: string
            type: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            search_type: choice
            options:
                label: oro.tax.system_configuration.fields.address_resolver_granularity.label
                required: true
                constraints:
                    - NotBlank: ~
                choice_translation_domain: messages
                choices:
                    oro.tax.system_configuration.fields.address_resolver_granularity.country.label: country
                    oro.tax.system_configuration.fields.address_resolver_granularity.region.label: region
                    oro.tax.system_configuration.fields.address_resolver_granularity.country_and_zip.label: country_and_zip_code
                    oro.tax.system_configuration.fields.address_resolver_granularity.zip.label: zip_code

        oro_tax.use_as_base_exclusions:
            data_type: array
            type: Oro\Bundle\TaxBundle\Form\Type\TaxBaseExclusionCollectionType
            options:
                label: oro.tax.system_configuration.fields.use_as_base.exclusions.label
                data_transformer: oro_tax.form.data_transformer.tax_base_exclusion_transformer

        oro_tax.destination:
            data_type: string
            type: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            search_type: choice
            options:
                label: oro.tax.system_configuration.fields.destination.label
                required: true
                constraints:
                    - NotBlank: ~
                choice_translation_domain: messages
                choices:
                    oro.tax.system_configuration.fields.destination.billing_address.label: billing_address
                    oro.tax.system_configuration.fields.destination.shipping_addressl.label: shipping_address

        oro_tax.digital_products_us:
            data_type: array
            type: Oro\Bundle\TaxBundle\Form\Type\ProductTaxCodeMultiSelectType
            options:
                label: oro.tax.system_configuration.fields.digital_products_us.label

        oro_tax.digital_products_eu:
            data_type: array
            type: Oro\Bundle\TaxBundle\Form\Type\ProductTaxCodeMultiSelectType
            options:
                label: oro.tax.system_configuration.fields.digital_products_eu.label

        oro_tax.origin_address:
            data_type: array
            type: Oro\Bundle\TaxBundle\Form\Type\OriginAddressType
            options:
                label: oro.tax.system_configuration.fields.origin_address.label

        oro_tax.shipping_tax_code:
            data_type: array
            type: Oro\Bundle\TaxBundle\Form\Type\ProductTaxCodeMultiSelectType
            options:
                label: oro.tax.system_configuration.fields.shipping_tax_code.label
                tooltip: oro.tax.system_configuration.fields.shipping_tax_code.tooltip

        oro_tax.shipping_rates_include_tax:
            data_type: boolean
            type: Oro\Bundle\ConfigBundle\Form\Type\ConfigCheckbox
            options:
                label: oro.tax.system_configuration.fields.shipping_rates_include_tax.label
                tooltip: oro.tax.system_configuration.fields.shipping_rates_include_tax.tooltip
                required: false

        oro_tax.calculate_taxes_after_promotions:
            data_type: boolean
            type: Oro\Bundle\ConfigBundle\Form\Type\ConfigCheckbox
            options:
                required: false
                label: oro.tax.system_configuration.fields.calculate_taxes_after_promotions.label
                tooltip: oro.tax.system_configuration.fields.calculate_taxes_after_promotions.tooltip

    tree:
        system_configuration:
            commerce:
                children:
                    taxation:
                        priority: 500
                        children:
                            tax_calculation:
                                priority: 100
                                children:
                                    tax_enable:
                                        priority: 100
                                        children:
                                            - oro_tax.tax_enable
                                    tax_provider:
                                        priority: 90
                                        children:
                                            - oro_tax.tax_provider
                                    tax_calculator:
                                        priority: 80
                                        children:
                                            - oro_tax.start_calculation_with
                                            - oro_tax.start_calculation_on
                                            - oro_tax.product_prices_include_tax
                                    tax_matcher:
                                        priority: 70
                                        children:
                                            - oro_tax.use_as_base_by_default
                                            - oro_tax.use_as_base_exclusions
                                            - oro_tax.destination
                                            - oro_tax.address_resolver_granularity
                                    origin_address:
                                        priority: 60
                                        children:
                                            - oro_tax.origin_address
                                    promotions:
                                        priority: 50
                                        children:
                                            - oro_tax.calculate_taxes_after_promotions
                            us_sales_tax:
                                priority: 90
                                children:
                                    tax_digital_products:
                                        children:
                                            - oro_tax.digital_products_us
                            eu_vat_tax:
                                priority: 90
                                children:
                                    tax_digital_products:
                                        children:
                                            - oro_tax.digital_products_eu

                            tax_shipping:
                                priority: 90
                                children:
                                    shipping_tax:
                                        children:
                                            - oro_tax.shipping_tax_code
                                            - oro_tax.shipping_rates_include_tax
        organization_configuration:
            commerce:
                children:
                    taxation:
                        priority: 500
                        children:
                            tax_shipping:
                                priority: 90
                                children:
                                    shipping_tax:
                                        children:
                                            - oro_tax.shipping_tax_code
                                            - oro_tax.shipping_rates_include_tax
        website_configuration:
            commerce:
                children:
                    taxation:
                        priority: 500
                        children:
                            tax_shipping:
                                priority: 90
                                children:
                                    shipping_tax:
                                        children:
                                            - oro_tax.shipping_tax_code
                                            - oro_tax.shipping_rates_include_tax
