services:
    oro_paypal.form.type.credit_card:
        class: Oro\Bundle\PayPalBundle\Form\Type\CreditCardType
        tags:
            - { name: form.type, alias: oro_paypal_credit_card }

    oro_paypal.form.type.credit_card_expiration_date:
        class: Oro\Bundle\PayPalBundle\Form\Type\CreditCardExpirationDateType
        tags:
            - { name: form.type, alias: oro_paypal_credit_card_expiration_date }

    oro_paypal.form.type.settings:
        class: Oro\Bundle\PayPalBundle\Form\Type\PayPalSettingsType
        arguments:
            - '@translator.default'
            - '@oro_paypal.settings.card_type.provider'
            - '@oro_paypal.settings.payment_action.provider'
        tags:
            - { name: form.type }
