Oro\Bundle\PayPalBundle\Entity\PayPalSettings:
    properties:
        creditCardLabels:
            - NotBlank: ~
        creditCardShortLabels:
            - NotBlank: ~
        expressCheckoutLabels:
            - NotBlank: ~
        expressCheckoutShortLabels:
            - NotBlank: ~
        expressCheckoutName:
            - NotBlank: ~
        creditCardPaymentAction:
            - NotBlank: ~
            - Valid: ~
        expressCheckoutPaymentAction:
            - NotBlank: ~
            - Valid: ~
        allowedCreditCardTypes:
            - NotBlank: ~
            - Valid: ~
        partner:
            - NotBlank: ~
            - Valid: ~
        vendor:
            - NotBlank: ~
            - Valid: ~
        user:
            - NotBlank: ~
            - Valid: ~
        password:
            - NotBlank: ~
            - Length:
                min: 7

Oro\Bundle\IntegrationBundle\Entity\Channel:
    constraints:
        - Oro\Bundle\PayPalBundle\Validator\Constraints\UniqueExpressCheckoutName: ~
