services:

    oro_pricing.product_kit.product_price_criteria.data_extractor.product_kit:
        class: Oro\Bundle\PricingBundle\ProductKit\ProductPriceCriteria\DataExtractor\ProductKitPriceCriteriaDataExtractor
        arguments:
            - '@oro_pricing.product_price_criteria_data_extractor'
        tags:
            - { name: oro_pricing.product_price_criteria_data_extractor }

    oro_pricing.product_kit.product_price_criteria.data_extractor.product_kit_item:
        class: Oro\Bundle\PricingBundle\ProductKit\ProductPriceCriteria\DataExtractor\ProductKitItemPriceCriteriaDataExtractor
        tags:
            - { name: oro_pricing.product_price_criteria_data_extractor }

    oro_pricing.product_kit.product_line_item_price_criteria.factory:
        class: Oro\Bundle\PricingBundle\ProductKit\ProductPriceCriteria\Factory\ProductKitLineItemPriceCriteriaFactory
        arguments:
            - '@oro_pricing.product_kit.product_price_criteria.builder'
        tags:
            - { name: oro_pricing.product_line_item_price_criteria.factory }

    oro_pricing.product_kit.product_price_by_matching_criteria.product_kit:
        class: Oro\Bundle\PricingBundle\ProductKit\PriceByMatchingCriteria\ProductKitPriceByMatchingCriteriaProvider
        arguments:
            - '@oro_pricing.provider.product_price_by_matching_criteria.simple'
            - '@oro_currency.rounding.price_rounding_service'
        tags:
            - { name: oro_pricing.provider.product_price_by_matching_criteria }

    oro_pricing.product_kit.product_line_item_price.factory.product_kit:
        class: Oro\Bundle\PricingBundle\ProductKit\ProductLineItemPrice\Factory\ProductKitLineItemPriceFactory
        arguments:
            - '@oro_pricing.product_line_item_price.factory'
            - '@oro_currency.rounding.price_rounding_service'
        tags:
            - { name: oro_pricing.product_line_item_price.factory }

    oro_pricing.product_kit.product_line_item_price.factory.product_kit_item:
        class: Oro\Bundle\PricingBundle\ProductKit\ProductLineItemPrice\Factory\ProductKitItemLineItemPriceFactory
        arguments:
            - '@oro_currency.rounding.price_rounding_service'
        tags:
            - { name: oro_pricing.product_line_item_price.factory }

    oro_pricing.product_kit.product_price_criteria.builder:
        class: Oro\Bundle\PricingBundle\ProductKit\ProductPriceCriteria\Builder\ProductKitPriceCriteriaBuilder
        arguments:
            - '@doctrine'
            - '@oro_pricing.user_currency_manager'
        calls:
            - ['setLogger', ['@logger']]
        tags:
            - { name: oro_pricing.product_price_criteria_builder }
            - { name: monolog.logger, channel: oro_pricing }
