services:
    oro_pricing.api.handle_price_list_status_change:
        class: 'Oro\Bundle\PricingBundle\Api\PriceList\Processor\HandlePriceListStatusChangeProcessor'
        arguments:
            - '@oro_pricing.price_list_relation_trigger_handler'
        tags:
            - { name: oro.api.processor, action: update, priority: -100, group: load_data, class: '%oro_pricing.entity.price_list.class%' }
            - { name: oro.api.processor, action: update, priority: -40, group: save_data, class: '%oro_pricing.entity.price_list.class%' }

    oro_pricing.api.update_price_list_lexemes:
        class: 'Oro\Bundle\PricingBundle\Api\PriceList\Processor\UpdatePriceListLexemesProcessor'
        arguments:
            - '@oro_pricing.hander.price_rule_lexeme_handler'
        tags:
            - { name: oro.api.processor, action: update, priority: -40, group: save_data, class: '%oro_pricing.entity.price_list.class%' }
            - { name: oro.api.processor, action: create, priority: -40, group: save_data, class: '%oro_pricing.entity.price_list.class%' }

    oro_pricing.api.build_combined_price_list_on_schedule_save:
        class: 'Oro\Bundle\PricingBundle\Api\PriceListSchedule\Processor\BuildCombinedPriceListOnScheduleSaveProcessor'
        arguments:
            - '@oro_pricing.builder.combined_price_list_activation_plan_builder'
        tags:
            - { name: oro.api.processor, action: create, priority: -40, group: save_data, class: '%oro_pricing.entity.price_list_schedule.class%' }
            - { name: oro.api.processor, action: update, priority: -40, group: save_data, class: '%oro_pricing.entity.price_list_schedule.class%' }

    oro_pricing.api.update_lexemes_price_rule_processor:
        class: 'Oro\Bundle\PricingBundle\Api\PriceRule\Processor\UpdateLexemesPriceRuleProcessor'
        arguments:
            - '@oro_pricing.hander.price_rule_lexeme_handler'
        tags:
            - { name: oro.api.processor, action: create, group: save_data, priority: -20, class: '%oro_pricing.entity.price_rule.class%' }
            - { name: oro.api.processor, action: update, group: save_data, priority: -20, class: '%oro_pricing.entity.price_rule.class%' }

    oro_pricing.api.update_lexemes_on_price_rule_delete_processor:
        class: 'Oro\Bundle\PricingBundle\Api\PriceRule\Processor\UpdateLexemesOnPriceRuleDeleteProcessor'
        arguments:
            - '@oro_pricing.hander.price_rule_lexeme_handler'
            - '@oro_api.delete.delete_data_by_handler'
        tags:
            - { name: oro.api.processor, action: delete, group: delete_data, priority: 10, class: '%oro_pricing.entity.price_rule.class%' }

    oro_pricing.api.update_lexemes_on_price_rule_delete_list_processor:
        class: 'Oro\Bundle\PricingBundle\Api\PriceRule\Processor\UpdateLexemesOnPriceRuleDeleteListProcessor'
        arguments:
            - '@oro_pricing.hander.price_rule_lexeme_handler'
            - '@oro_api.delete_list.delete_data_by_handler'
        tags:
            - { name: oro.api.processor, action: delete_list, group: delete_data, priority: -15, class: '%oro_pricing.entity.price_rule.class%' }

    oro_pricing.api_form_subscriber.add_schedules_to_price_list:
        class: 'Oro\Bundle\PricingBundle\Api\PriceListSchedule\Form\AddSchedulesToPriceListApiFormSubscriber'

    oro_pricing.api.on_schedule_delete_list_processor:
        parent: 'oro_api.delete_list.delete_data_by_handler'
        tags:
            - { name: oro.api.processor, action: delete_list, priority: -15, group: delete_data, class: '%oro_pricing.entity.price_list_schedule.class%' }

    oro_pricing.api.build_combined_price_list_on_schedule_delete_list:
        class: 'Oro\Bundle\PricingBundle\Api\PriceListSchedule\Processor\BuildCombinedPriceListOnScheduleDeleteListProcessor'
        public: false
        decorates: oro_pricing.api.on_schedule_delete_list_processor
        arguments:
            - '@oro_pricing.builder.combined_price_list_activation_plan_builder'
            - '@oro_pricing.api.build_combined_price_list_on_schedule_delete_list.inner'

    oro_pricing.api.update_price_list_contains_schedule_on_schedule_delete_list:
        class: 'Oro\Bundle\PricingBundle\Api\PriceListSchedule\Processor\UpdatePriceListContainsScheduleOnScheduleDeleteListProcessor'
        public: false
        decorates: oro_pricing.api.on_schedule_delete_list_processor
        arguments:
            - '@oro_entity.doctrine_helper'
            - '@oro_pricing.api.update_price_list_contains_schedule_on_schedule_delete_list.inner'

    oro_pricing.api.on_schedule_delete_processor:
        parent: 'oro_api.delete.delete_data_by_handler'
        tags:
            - { name: oro.api.processor, action: delete, priority: 10, group: delete_data, class: '%oro_pricing.entity.price_list_schedule.class%' }

    oro_pricing.api.update_price_list_contains_schedule_on_schedule_delete:
        class: 'Oro\Bundle\PricingBundle\Api\PriceListSchedule\Processor\UpdatePriceListContainsScheduleOnScheduleDeleteProcessor'
        public: false
        decorates: oro_pricing.api.on_schedule_delete_processor
        arguments:
            - '@oro_entity.doctrine_helper'
            - '@oro_pricing.api.update_price_list_contains_schedule_on_schedule_delete.inner'

    oro_pricing.api.build_combined_price_list_on_schedule_delete:
        class: 'Oro\Bundle\PricingBundle\Api\PriceListSchedule\Processor\BuildCombinedPriceListOnScheduleDeleteProcessor'
        public: false
        decorates: oro_pricing.api.on_schedule_delete_processor
        arguments:
            - '@oro_pricing.builder.combined_price_list_activation_plan_builder'
            - '@oro_pricing.api.build_combined_price_list_on_schedule_delete.inner'

    oro_pricing.api.price_list_relation_trigger_handler_for_website_and_customer_group:
        class: 'Oro\Bundle\PricingBundle\Api\Processor\PriceListRelationTriggerHandlerForWebsiteAndCustomerGroupProcessor'
        arguments:
            - '@oro_pricing.price_list_relation_trigger_handler'
        tags:
            - { name: oro.api.processor, action: create, group: save_data, priority: -40, class: '%oro_pricing.entity.price_list_customer_group_fallback.class%' }
            - { name: oro.api.processor, action: update, group: save_data, priority: -40, class: '%oro_pricing.entity.price_list_customer_group_fallback.class%' }
            - { name: oro.api.processor, action: delete, group: delete_data, priority: 0, class: '%oro_pricing.entity.price_list_customer_group_fallback.class%' }
            - { name: oro.api.processor, action: delete_list, group: delete_data, priority: 0, class: '%oro_pricing.entity.price_list_customer_group_fallback.class%' }
            - { name: oro.api.processor, action: create, group: save_data, priority: -40, class: '%oro_pricing.entity.price_list_to_customer_group.class%' }
            - { name: oro.api.processor, action: update, group: save_data, priority: -40, class: '%oro_pricing.entity.price_list_to_customer_group.class%' }
            - { name: oro.api.processor, action: delete, group: delete_data, priority: 0, class: '%oro_pricing.entity.price_list_to_customer_group.class%' }
            - { name: oro.api.processor, action: delete_list, group: delete_data, priority: 0, class: '%oro_pricing.entity.price_list_to_customer_group.class%' }

    oro_pricing.api.price_list_relation_trigger_handler_for_website_and_customer:
        class: 'Oro\Bundle\PricingBundle\Api\Processor\PriceListRelationTriggerHandlerForWebsiteAndCustomerProcessor'
        arguments:
            - '@oro_pricing.price_list_relation_trigger_handler'
        tags:
            - { name: oro.api.processor, action: create, group: save_data, priority: -40, class: '%oro_pricing.entity.price_list_customer_fallback.class%' }
            - { name: oro.api.processor, action: update, group: save_data, priority: -40, class: '%oro_pricing.entity.price_list_customer_fallback.class%' }
            - { name: oro.api.processor, action: delete, group: delete_data, priority: 0, class: '%oro_pricing.entity.price_list_customer_fallback.class%' }
            - { name: oro.api.processor, action: delete_list, group: delete_data, priority: 0, class: '%oro_pricing.entity.price_list_customer_fallback.class%' }
            - { name: oro.api.processor, action: create, group: save_data, priority: -40, class: '%oro_pricing.entity.price_list_to_customer.class%' }
            - { name: oro.api.processor, action: update, group: save_data, priority: -40, class: '%oro_pricing.entity.price_list_to_customer.class%' }
            - { name: oro.api.processor, action: delete, group: delete_data, priority: 0, class: '%oro_pricing.entity.price_list_to_customer.class%' }
            - { name: oro.api.processor, action: delete_list, group: delete_data, priority: 0, class: '%oro_pricing.entity.price_list_to_customer.class%' }

    oro_pricing.api.set_price_by_value_and_currency:
        class: 'Oro\Bundle\CurrencyBundle\Api\Processor\SetPriceByValueAndCurrencyProcessor'
        tags:
            - { name: oro.api.processor, action: update, group: load_data, priority: -50, class: '%oro_pricing.entity.product_price.class%' }
            - { name: oro.api.processor, action: create, group: load_data, priority: -50, class: '%oro_pricing.entity.product_price.class%' }
            - { name: oro.api.processor, action: update, group: load_data, priority: -50, class: '%oro_pricing.entity.price_attribute_product_price.class%' }
            - { name: oro.api.processor, action: create, group: load_data, priority: -50, class: '%oro_pricing.entity.price_attribute_product_price.class%' }

    oro_pricing.api.normalize_product_price_id:
        class: 'Oro\Bundle\PricingBundle\Api\ProductPrice\Processor\NormalizeInputProductPriceIdProcessor'
        arguments:
            - '@oro_pricing.api.price_list_id_in_context_storage'
            - '@oro_api.doctrine_helper'
            - '@validator'
        tags:
            - { name: oro.api.processor, action: get, group: normalize_input, requestType: rest, priority: -120, class: '%oro_pricing.entity.product_price.class%' }
            - { name: oro.api.processor, action: delete, group: normalize_input, requestType: rest, priority: -120, class: '%oro_pricing.entity.product_price.class%' }
            - { name: oro.api.processor, action: update, group: normalize_input, requestType: rest, priority: -120, class: '%oro_pricing.entity.product_price.class%' }

    oro_pricing.api.price_list_id_in_context_storage:
        class: 'Oro\Bundle\PricingBundle\Api\ProductPrice\PriceListIDInContextStorage'

    oro_pricing.api.product_price_id_by_price_list_id_normalizer:
        class: 'Oro\Bundle\PricingBundle\Api\ProductPrice\ProductPriceIDByPriceListIDNormalizer'
        arguments:
            - '@oro_pricing.api.price_list_id_in_context_storage'

    oro_pricing.api.normalize_product_price:
        class: 'Oro\Bundle\PricingBundle\Api\ProductPrice\Processor\NormalizeOutputProductPriceIdProcessor'
        arguments:
            - '@oro_pricing.api.product_price_id_by_price_list_id_normalizer'
        tags:
            - { name: oro.api.processor, action: get, group: load_data, priority: -20, class: '%oro_pricing.entity.product_price.class%' }
            - { name: oro.api.processor, action: get_list, group: load_data, priority: -20, class: '%oro_pricing.entity.product_price.class%' }

    oro_pricing.api.set_price_list_in_context_by_product_price_processor:
        class: 'Oro\Bundle\PricingBundle\Api\ProductPrice\Processor\StorePriceListInContextByProductPriceProcessor'
        arguments:
            - '@oro_pricing.api.price_list_id_in_context_storage'
        tags:
            - { name: oro.api.processor, action: create, group: save_data, priority: 0, class: '%oro_pricing.entity.product_price.class%' }
            - { name: oro.api.processor, action: update, group: save_data, priority: 0, class: '%oro_pricing.entity.product_price.class%' }

    oro_pricing.update.load_normalized_entity:
        class: 'Oro\Bundle\PricingBundle\Api\ProductPrice\Processor\LoadNormalizedProductPriceWithNormalizedIdProcessor'
        arguments:
            - '@oro_api.action_processor_bag'
            - '@oro_pricing.api.product_price_id_by_price_list_id_normalizer'
        tags:
            - { name: oro.api.processor, action: update, group: normalize_data, priority: 0, class: '%oro_pricing.entity.product_price.class%'}
            - { name: oro.api.processor, action: create, group: normalize_data, priority: 0, class: '%oro_pricing.entity.product_price.class%'}

    oro_pricing.api.set_price_list_in_context_by_filter:
        class: 'Oro\Bundle\PricingBundle\Api\ProductPrice\Processor\StorePriceListInContextByFilterProcessor'
        arguments:
            - '@oro_pricing.api.price_list_id_in_context_storage'
            - '@oro_api.doctrine_helper'
        tags:
            - { name: oro.api.processor, action: get_list, group: normalize_input, priority: -120, class: '%oro_pricing.entity.product_price.class%' }
            - { name: oro.api.processor, action: delete_list, group: normalize_input, priority: -120, class: '%oro_pricing.entity.product_price.class%' }

    oro_pricing.api.build_single_item_query:
        class: Oro\Bundle\ApiBundle\Processor\Shared\BuildSingleItemQuery
        arguments:
            - '@oro_api.doctrine_helper'
            - '@oro_api.criteria_connector'
            - '@oro_api.entity_id_helper'
        tags:
            - { name: oro.api.processor, action: update, group: load_data, priority: 10, class: '%oro_pricing.entity.product_price.class%' }
            - { name: oro.api.processor, action: delete, group: load_data, priority: 10, class: '%oro_pricing.entity.product_price.class%' }

    oro_pricing.api.load_entity_by_orm_query:
        class: Oro\Bundle\ApiBundle\Processor\Shared\LoadEntityByOrmQuery
        tags:
            - { name: oro.api.processor, action: update, group: load_data, priority: 0, class: '%oro_pricing.entity.product_price.class%' }
            - { name: oro.api.processor, action: delete, group: load_data, priority: 0, class: '%oro_pricing.entity.product_price.class%' }

    oro_pricing.api.enabled_price_sharding_on_query:
        class: 'Oro\Bundle\PricingBundle\Api\ProductPrice\Processor\EnableShardingOnQueryProcessor'
        arguments:
          - '@oro_pricing.shard_manager'
          - '@oro_pricing.api.price_list_id_in_context_storage'
        tags:
            - { name: oro.api.processor, action: update, group: load_data, priority: 5, class: '%oro_pricing.entity.product_price.class%' }
            - { name: oro.api.processor, action: delete, group: load_data, priority: 5, class: '%oro_pricing.entity.product_price.class%' }
            - { name: oro.api.processor, action: delete_list, group: build_query, priority: -255, class: '%oro_pricing.entity.product_price.class%' }

    oro_pricing.api.enable_price_sharding_on_config:
        class: 'Oro\Bundle\PricingBundle\Api\ProductPrice\Processor\EnableShardingOnConfigProcessor'
        arguments:
            - '@oro_pricing.shard_manager'
            - '@oro_pricing.api.price_list_id_in_context_storage'
        tags:
            - { name: oro.api.processor, action: get_list, group: build_query, priority: -255, class: '%oro_pricing.entity.product_price.class%' }
            - { name: oro.api.processor, action: get, group: build_query, priority: -255, class: '%oro_pricing.entity.product_price.class%' }

    oro_pricing.api.save_product_price:
        class: 'Oro\Bundle\PricingBundle\Api\ProductPrice\Processor\SaveProductPriceProcessor'
        arguments:
            - '@oro_pricing.manager.price_manager'
        tags:
            - { name: oro.api.processor, action: update, group: save_data, priority: -5, class: '%oro_pricing.entity.product_price.class%' }
            - { name: oro.api.processor, action: create, group: save_data, priority: -5, class: '%oro_pricing.entity.product_price.class%' }

    oro_pricing.api.price_manager_delete_handler:
        parent: 'oro_soap.handler.delete'
        class: 'Oro\Bundle\PricingBundle\Api\ProductPrice\Delete\PriceManagerDeleteHandler'
        arguments:
            - '@oro_pricing.manager.price_manager'

    oro_pricing.api.reset_price_rule_field_on_update:
        class: 'Oro\Bundle\PricingBundle\Api\ProductPrice\Processor\ResetPriceRuleFieldOnUpdateProcessor'
        tags:
            - { name: oro.api.processor, action: update, priority: -45, group: load_data, class: '%oro_pricing.entity.product_price.class%' }
            - { name: oro.api.processor, action: update, priority: 0, group: save_data, class: '%oro_pricing.entity.product_price.class%' }
