parameters:
    optional_search_listeners:
        - 'oro_search.index_listener'
        - 'oro_website.indexation_request_listener'
        - 'oro_website_search.reindex_request.listener'

services:
    oro_product.alias.provider.content_variant_segment_provider:
        alias: oro_product.provider.content_variant_segment_provider

    oro_checkout.alias.mapper.order_mapper:
        alias: oro_checkout.mapper.order_mapper

    oro_website.manager.stub:
        class: Oro\Bundle\WebsiteBundle\Tests\Functional\Stub\WebsiteManagerStub
        decorates: oro_website.manager
        decoration_priority: -256 # should be at the top of the decoration chain
        arguments:
            - '@.inner'
            - '@oro_website.cache.website'

    oro_promotion.alias.provider.matching_products_provider:
        alias: oro_promotion.provider.matching_products_provider
