search:
    Oro\Bundle\ShoppingListBundle\Entity\ShoppingList:
        alias:                          oro_shopping_list
        route:
            name:                       oro_shopping_list_view
            parameters:
                id:                     id
        search_template:                '@OroShoppingList/ShoppingList/searchResult.html.twig'
        fields:
            -
                name:                   label
                target_type:            text
                target_fields:          [label]
