features:
    manage_shipping_rules:
        label: oro.shipping.shippingmethodsconfigsrule.feature.manage.label
        description: oro.shipping.shippingmethodsconfigsrule.feature.manage.description
        allow_if_all_abstain: true
        routes:
            - oro_shipping_methods_configs_rule_index
            - oro_shipping_methods_configs_rule_create
            - oro_shipping_methods_configs_rule_view
            - oro_shipping_methods_configs_rule_update
            - oro_status_shipping_rule_massaction
            - oro_api_enable_shippingrules
            - oro_api_disable_shippingrules
        navigation_items:
            - application_menu.system_tab.shipping_rule
            - shortcuts.shortcut_shipping_rule
