aliases:
    oro/filter/frontend-product-price-filter$: oropricing/js/filter/frontend-product-price-filter
    oro/filter/product-price-filter$: oropricing/js/filter/product-price-filter
dynamic-imports:
    commons:
        - oropricing/js/app/views/list-item-product-prices-view
    orodatagrid:
        - oro/filter/frontend-product-price-filter
        - oro/filter/product-price-filter
    oroproduct:
        - oropricing/js/app/components/currency-switcher-component
        - oropricing/js/app/components/list-item-product-prices-component
        - oropricing/js/app/components/totals-component
        - oropricing/js/app/views/base-product-matrix-view
        - oropricing/js/app/views/line-item-product-prices-view
        - oropricing/js/app/views/product-total-price-view
        - oropricing/js/app/views/quick-add-row-price-view
map:
    '*':
        oropricing/templates/order/subtotals.html: oropricing/templates/order/frontend/subtotals.html
        oropricing/templates/order/totals.html: oropricing/templates/order/frontend/totals.html
