layout:
    imports:
        - oro_product_grid

    actions:
        - '@setOption':
            id: product_datagrid
            optionName: grid_name
            optionValue: frontend-product-search-grid

        - '@setOption':
            id: product_datagrid
            optionName: current_row_view
            optionValue: '=data["oro_product_datagrid_row_view"].getThemeByGridName("frontend-product-search-grid")'

        - '@setOption':
            id: product_datagrid_toolbar_display_options
            optionName: current_row_view
            optionValue: '=data["oro_product_datagrid_row_view"].getThemeByGridName("frontend-product-search-grid")'
