services:
    # Request form types
    oro_rfp.form.type.request:
        class: 'Oro\Bundle\RFPBundle\Form\Type\RequestType'
        calls:
            - [setDataClass, ['Oro\Bundle\RFPBundle\Entity\Request']]
        tags:
            - { name: form.type, alias: oro_rfp_request }

    oro_rfp.form.type.user_select:
        class: 'Oro\Bundle\RFPBundle\Form\Type\UserSelectType'
        arguments:
            - "@doctrine"
        tags:
            - { name: form.type, alias: oro_rfp_user_select }

    oro_rfp.form.type.request_product:
        class: 'Oro\Bundle\RFPBundle\Form\Type\RequestProductType'
        calls:
            - [setDataClass, ['Oro\Bundle\RFPBundle\Entity\RequestProduct']]
        tags:
            - { name: form.type, alias: oro_rfp_request_product }

    oro_rfp.form.type.request_product_item:
        class: 'Oro\Bundle\RFPBundle\Form\Type\RequestProductItemType'
        calls:
            - [setDataClass, ['Oro\Bundle\RFPBundle\Entity\RequestProductItem']]
        tags:
            - { name: form.type, alias: oro_rfp_request_product_item }

    oro_rfp.form.type.request_product_collection:
        class: 'Oro\Bundle\RFPBundle\Form\Type\RequestProductCollectionType'
        tags:
            - { name: form.type, alias: oro_rfp_request_product_collection }

    oro_rfp.form.type.request_product_item_collection:
        class: 'Oro\Bundle\RFPBundle\Form\Type\RequestProductItemCollectionType'
        tags:
            - { name: form.type, alias: oro_rfp_request_product_item_collection }

    oro_rfp.form.type.frontend_request_product_item_collection:
            class: 'Oro\Bundle\RFPBundle\Form\Type\Frontend\RequestProductItemCollectionType'
            tags:
                - { name: form.type, alias: oro_rfp_frontend_request_product_item_collection }

    oro_rfp.form.type.frontend_request:
        class: 'Oro\Bundle\RFPBundle\Form\Type\Frontend\RequestType'
        calls:
            - [setDataClass, ['Oro\Bundle\RFPBundle\Entity\Request']]
        tags:
            - { name: form.type, alias: oro_rfp_frontend_request }

    oro_rfp.form.type.frontend_request_product:
        class: 'Oro\Bundle\RFPBundle\Form\Type\Frontend\RequestProductType'
        calls:
            - [setDataClass, ['Oro\Bundle\RFPBundle\Entity\RequestProduct']]
        tags:
            - { name: form.type, alias: oro_rfp_frontend_request_product }

    oro_rfp.form.type.frontend_request_product_collection:
        class: 'Oro\Bundle\RFPBundle\Form\Type\Frontend\RequestProductCollectionType'
        tags:
            - { name: form.type, alias: oro_rfp_frontend_request_product_collection }

    oro_rfp.form.type.extension.frontend_request_data_storage:
        class: 'Oro\Bundle\RFPBundle\Form\Extension\RequestDataStorageExtension'
        arguments:
            - '@request_stack'
            - '@oro_product.storage.product_data_storage'
            - '@form.property_accessor'
            - '@doctrine'
            - '@logger'
            - '@oro_rfp.provider.product_availability'
            - '@translator'
            - '@twig'
        tags:
            - { name: form.type_extension }

    oro_rfp.form.type.extension.order_line_item_data_storage:
        class: 'Oro\Bundle\RFPBundle\Form\Extension\OrderLineItemDataStorageExtension'
        arguments:
            - "@request_stack"
            - "@oro_rfp.storage.offers_data_storage"
            - "@oro_rfp.storage.offers_form_storage"
        tags:
            - { name: form.type_extension, alias: oro_order_line_item, extended_type: Oro\Bundle\OrderBundle\Form\Type\OrderLineItemType, priority: 5 }
            - { name: oro_featuretogle.feature, feature: rfp }

    oro_rfp.form.type.extension.order_data_storage:
        class: 'Oro\Bundle\RFPBundle\Form\Extension\OrderDataStorageExtension'
        arguments:
            - '@request_stack'
            - '@oro_pricing.provider.product_price'
            - '@oro_pricing.model.product_price_scope_criteria_factory'
            - '@oro_pricing.product_price_criteria_factory'
        tags:
            - { name: form.type_extension }
            - { name: oro_featuretogle.feature, feature: rfp }

    oro_rfp.form.type.request_offers:
        class: 'Oro\Bundle\RFPBundle\Form\Type\OffersType'
        tags:
            - { name: form.type, alias: oro_rfp_request_offers }
