services:
    oro_rfp.tests.entity_name_resolver.data_loader:
        class: Oro\Bundle\RFPBundle\Tests\Functional\Environment\TestEntityNameResolverDataLoader
        decorates: oro_entity.tests.entity_name_resolver.data_loader
        arguments:
            - '@.inner'

    oro_rfp.tests.product_kit.factory.request_product_kit_item_line_item:
        parent: oro_rfp.product_kit.factory.request_product_kit_item_line_item
        decorates: oro_rfp.product_kit.factory.request_product_kit_item_line_item
        public: true
