services:
    oro_rfp.api.processor.update_request_data_for_request_entity:
        class: 'Oro\Bundle\RFPBundle\Api\Processor\UpdateRequestDataForRequestEntity'
        tags:
            - { name: oro.api.processor, action: create, group: load_data, priority: -50, class: '%oro_rfp.entity.request.class%' }
            - { name: oro.api.processor, action: update, group: load_data, priority: -50, class: '%oro_rfp.entity.request.class%' }

    oro_rfp.api.processor.update_request_data_for_request_product_item:
        class: 'Oro\Bundle\RFPBundle\Api\Processor\UpdateRequestDataForRequestProductItem'
        tags:
            - { name: oro.api.processor, action: create, group: load_data, priority: -50, class: '%oro_rfp.entity.request_product_item.class%' }
            - { name: oro.api.processor, action: update, group: load_data, priority: -50, class: '%oro_rfp.entity.request_product_item.class%' }
